### ISSUE TITLE
Zdash Rpc update stats

### ISSUE THREAD

**Issue by sonicdx10** [z-classic/z-nomp#100]
Well Rpc Updating Stats is not working but I can confirm that payments are made in zdash

**Comment by aayanl** [comment]
It's an issue with zdash's RPC

**Comment by sonicdx10** [comment]
good to see this one open again

**Comment by zcashcloud** [comment]
Hi
modify libs/paymentProcessor.js  - line 306 from this                        

_finalRedisCommands.push(['hset', coin + ':stats', 'networkSols', result[0].response.networksolps]);_

to this 

**finalRedisCommands.push(['hset', coin + ':stats', 'networkSols', result[0].**response.networkhashps**]);**

All works

**Comment by sonicdx10** [comment]
testing right away!

**Comment by sonicdx10** [comment]
well yeah it delets the error message while trying to update stats in zdash, but still no newtork stats are showing up on web

**Comment by sonicdx10** [comment]
my bad, it is working ok! Thx @zcashcloud

**Comment by sonicdx10** [comment]
@aayanl @sennevb @hellcatz You may want to merge this solution 🥇

**Comment by zcashcloud** [comment]
@sonicdx10 you are welcome

**Comment by aayanl** [comment]
So zdash hasn't pulled v1.0.3 from zcash yet, eek

**Comment by sonicdx10** [comment]
This week I really not sure if willl be .05+ version or the win wallet, but both are in plans of dev so we can wait the update or maybe both of em 😆

**Comment by sennevb** [comment]
Hi
modify libs/paymentProcessor.js - line 306 from this

finalRedisCommands.push(['hset', coin + ':stats', 'networkSols', result[0].response.networksolps]);

to this

finalRedisCommands.push(['hset', coin + ':stats', 'networkSols', result[0].response.networkhashps]);

All works

also Zcash and so wil lstil work if you change this, or do we have to make an if statement???

@aayanl will not be merged??

**Comment by sonicdx10** [comment]
So if Zdash team update the soft to .5+ wee need to set it back as it was? 😲

**Comment by sennevb** [comment]
then its best to wait lol

**Comment by sonicdx10** [comment]
It's seems that everything work properly with your solution, I prefer it than wait 🚽 HAHA

**Comment by sennevb** [comment]
does it work for zdash only, or does Zcash and zclassic also still work with this workaround??

**Comment by sonicdx10** [comment]
Well, the truth is that I have not found any blocks in either of those two, but the "rpc" has not pointed out any error, nor the node (there is no illegal function in the procedure)

**Comment by sennevb** [comment]
i changed the line like mentioned above, still getting:
2017-04-10 18:47:28 [Pool]      [zcash] (Thread 1) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocksubsidy","params":[],"id":1491842848733}
Reponse Data: Work queue depth exceeded

**Comment by cristiycv** [comment]
Is the zdash/hush working? I have installed z-nomp with zcash and zdash, but i'm not sure about zdash config, I don't find any block... is used the default diff settings..
