### ISSUE TITLE
Komodo - User Stats

### ISSUE THREAD

**Issue by sonicdx10** [z-classic/z-nomp#101]
Komodo user stats are not displaying on web

**Comment by Ingham27** [comment]
https://github.com/Ingham27/z-nomp/commit/74bf6705829f377bcad0f8edf3032566c50a793e#diff-9bd4f6285ed660df185fe391790daa65

**Comment by sonicdx10** [comment]
& t- ones? sup to be a multi-equi-p isn't?

**Comment by sonicdx10** [comment]
#101 This should fix missing komodo user stats on web page

`					if (address != null && address.length > 0 && address.startsWith('t'),('R')) { `
