### ISSUE TITLE
Could not dumpprivkey for zcash

### ISSUE THREAD

**Issue by fittsy** [z-classic/z-nomp#103]
I am getting the following error when trying to "npm start"
[zcash] Could not dumpprivkey for zcash {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}

Then later:
2017-03-21 15:15:50 [Pool]      [zcash] (Thread 1) Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:18232"}

I know my RPC service is running because I can  ./src/zcash-cli getinfo

I apologize if I'm doing something daft. I even allowed 19332 and 18232 in the firewall just in case that was my issue.

**Comment by aayanl** [comment]
check if you're using the right rpc ports, zclassic/zcash default rpcport is 8232. Make sure you keep this port firewalled off otherwise anyone can steal the key

**Comment by aayanl** [comment]
Closed due to inactivity

**Comment by downsun** [comment]
How did you solve it? I met the same problem.
