### ISSUE TITLE
Zdash rpc stats not working

### ISSUE THREAD

**Issue by sennevb** [z-classic/z-nomp#105]
Zdash is not showing network stats in stats page

**Comment by sonicdx10** [comment]
#100 already issued

**Comment by sennevb** [comment]
Sorry didnt noticed

Op 25 mrt. 2017 6:24 p.m. schreef "sonicdx10" <notifications@github.com>:

**Comment by sennevb** [comment]
i got this line from the pool:

 Could not update zcash stats to redis {"command":"EXEC","code":"EXECABORT","errors":[{"command":"HSET","args":["zdash:stats","networkSols"],"code":"ERR","position":2}]}

this is why we have no stats..

**Comment by sonicdx10** [comment]
yeah but it is like something about zdash code, because payments are made without problems

**Comment by aayanl** [comment]
Zcash doesn't have a stable wallet and I have no idea how to get it working

**Comment by sonicdx10** [comment]
Well, in fact, it is working, but is not refreshing stats on web, just that
