### ISSUE TITLE
z-nomp crashed website

### ISSUE THREAD

**Issue by sennevb** [z-classic/z-nomp#106]
undefined:3
var out='<style>\n    #topCharts{\n        padding: 18px;\n    }\n    #topCharts > div > div > svg{\n        display: block;\n        height: 280px;\n    }\n    .chartWrapper{\n        border: solid 1px #c7c7c7;\n        border-radius: 5px;\n        padding: 5px;\n        margin-bottom: 18px;\n    }\n    .chartLabel{\n        font-size: 1.2em;\n        text-align: center;\n        padding: 4px;\n    }\n    .chartHolder{\n\n    }\n\t\n\t#boxesLower {\n        margin: 0 9px;\n    }\n    #boxesLower > div {\n        display: flex;\n    }\n    #boxesLower > div > div {\n        flex: 1 1 auto;\n        margin: 0 9px 18px 9px;\n        padding: 10px;\n        display: flex;\n        flex-direction: column;\n    }\n    .boxLowerHeader{\n        font-size: 1.3em;\n        margin: 0 0 5px 10px;\n    }\n    #boxStatsLeft{\n        color: black;\n        background-color: #cccccc;\n    }\n    #boxStatsRight{\n\t\tcolor: black;\n        background-color: #cccccc;\n    }\n    .boxStats{\n        color: whit

TypeError: Cannot read property '0000010a4e5d7800d5ee1a3704008b2b1a5e4863d4eb723e085d3e2974b0edb5' of null
    at Object.eval [as stats] (eval at doT.template (/root/pool/node_modules/dot/doT.js:132:11), <anonymous>:3:6032)
    at processTemplates (/root/pool/libs/website.js:61:62)
    at /root/pool/libs/website.js:93:13
    at /root/pool/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/root/pool/node_modules/async/dist/async.js:935:13)
    at /root/pool/node_modules/async/dist/async.js:843:16
    at /root/pool/libs/website.js:86:17
    at tryToString (fs.js:447:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:434:12)

any clues??

**Comment by sennevb** [comment]
can start it anymore..

**Comment by sennevb** [comment]
its has somethign to do with z-dash, disabling this coin fixes the crash..

**Comment by sonicdx10** [comment]
please copy paste your coin.json

**Comment by sennevb** [comment]
i left it running for a while without zdash ,enabled again and is working :-)
