### ISSUE TITLE
Zcash update: rpc not working??

### ISSUE THREAD

**Issue by sennevb** [z-classic/z-nomp#110]
[zcash] (Thread 5) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocksubsidy","params":[],"id":1491587901942}
Reponse Data: Work queue depth exceeded

**Comment by aayanl** [comment]
Usually this happens if too many requests comes into the node,investigating

**Comment by sennevb** [comment]
2017-04-08 18:02:14 [Pool]      [zcash] (Thread 5) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocktemplate","params":[{"capabilities":["coinbasetxn","workid","coinbase/append"]}],"id":1491667334320}
Reponse Data: Work queue depth exceeded
2017-04-08 18:02:14 [Pool]      [zcash] (Thread 8) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocktemplate","params":[{"capabilities":["coinbasetxn","workid","coinbase/append"]}],"id":1491667334318}
Reponse Data: Work queue depth exceeded

**Comment by aayanl** [comment]
Also can you give me the system specs z-nomp is running on and zcash's node version?

**Comment by sonicdx10** [comment]
maybe memory prob?

**Comment by sennevb** [comment]
64gb ram should be enough??
increasing to 100 solves the problem!!

**Comment by sennevb** [comment]
also server load is halving after this, what is the disadvantage of making this value bigger??

**Comment by hellcatz** [comment]
It is the block polling interval. It is how often z-nomp checks the coin daemon for new blocks to update/notify workers. 100 = 100ms  (roughly 10 times a second it checks)

**Comment by sennevb** [comment]
100ms isnt that bad! should be good

**Comment by cryptozeny** [comment]
@aayanl @sennevb thanks!

i did `blockRefreshInterval` to `100`. 50 was too fast and had sync issue.

```js
2019-02-01 03:58:58 [Pool]    [sugarchain] (Thread 3) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocktemplate","params":[{"capabilities":["coinbasetxn","workid","coinbase/append"],"rules":["segwit"]}],"id":1548961138153}
Reponse Data: Work queue depth exceeded
2019-02-01 03:58:58 [Pool]    [sugarchain] (Thread 1) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocktemplate","params":[{"capabilities":["coinbasetxn","workid","coinbase/append"],"rules":["segwit"]}],"id":1548961138155}
Reponse Data: Work queue depth exceeded
2019-02-01 03:58:58 [Pool]    [sugarchain] (Thread 4) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocktemplate","params":[{"capabilities":["coinbasetxn","workid","coinbase/append"],"rules":["segwit"]}],"id":1548961138170}
Reponse Data: Work queue depth exceeded
```
