### ISSUE TITLE
How to reject invalid sharing

### ISSUE THREAD

**Issue by ceozero** [z-classic/z-nomp#112]
I set up a DWC mine pool, because the confusion of DWC is different from ZEC, the use of mining software is different, but I can not refuse to share from the ZEC mining software. Because ZEC mining software is unable to find any block.
How can I refuse to share from ZEC mining software?
this is  zec {  memcpy(personalization, "ZcashPoW", 9);  }
this is dwc { memcpy(personalization, "DeepWebCa", 9); }
@joshuayabut @aayanl

**Comment by sennevb** [comment]
its a different algo, you cant use z-nomp for this..

**Comment by ceozero** [comment]
for where？

**Comment by sennevb** [comment]
Zclassic uses equihash algorithm , seems DWC uses another algo, so its not going to work

**Comment by aayanl** [comment]
It uses a modified version of Equihash, I'll happily accept a PR for it. It just needs its own entry in algopropties https://github.com/z-classic/node-stratum-pool

**Comment by ceozero** [comment]
@aayanl  give me you email.
I need a private custom.

**Comment by aayanl** [comment]
Tell the dev to come onto here and tell me what did they change to equihash

**Comment by ceozero** [comment]
@aayanl I need a private custom. Not open.

**Comment by ceozero** [comment]
call me   ceozero@me.com    @aayanl
