### ISSUE TITLE
website files may not be reloading

### ISSUE THREAD

**Issue by hellcatz** [z-classic/z-nomp#118]
```
(node:2363) DeprecationWarning: (node-watch) First param in callback function  is replaced with event name since 0.5.0, use  `(evt, filename) => {}` if you want to get the filename
```
node-watch used to reload `website` files is may not be working with latest npm package updates
https://github.com/z-classic/z-nomp/blob/master/libs/website.js#L98-L106

**Comment by sennevb** [comment]
i noticed this also, you need to restart pool to see changes on frontend

**Comment by aayanl** [comment]
Sigh, JavaScript. Always breaking old code with updates

**Comment by hellcatz** [comment]
I was able to test a quick fix...and it worked...
However, I need to understand the consequences more...
I'll have some code changes to test later today possibly...

**Comment by yuanchuan** [comment]
Sorry for the breaking. 

I suggest replacing all the "*" in `package.json` with prefixed tilde(~) or caret(^) version numbers to prevent something like this to happen again. (see https://docs.npmjs.com/files/package.json)

Some tools might be help:

https://yarnpkg.com/en/
https://docs.npmjs.com/cli/shrinkwrap

**Comment by aayanl** [comment]
It's fine, I made a PR to lockdown package versions #122
