### ISSUE TITLE
Add additional payment schemes:

### ISSUE THREAD

**Issue by aayanl** [z-classic/z-nomp#127]
<ul>
<li>PPLNS </li>
<li><a href="https://github.com/z-classic/z-nomp/issues/127#issuecomment-297184900"><s>PPLNT (pay per set amount of time :D) #132</s></a></li>
<li><a href="https://github.com/z-classic/z-nomp/issues/127#issuecomment-302277294"> Suicidal modes. </a></li>
</ul>

Leave suggestions below if you want to see anything else

**Comment by hellcatz** [comment]
Pay Per Last N Time Shares (PPLNT)
Block rounds are defined by a set time period.
To qualify your shares during the round for payment,
mine for at least 51% of the time period in the round.

**Comment by sennevb** [comment]
we need this!

**Comment by aayanl** [comment]
#132

**Comment by aayanl** [comment]
PPLNT is now in the master branch 🥇

**Comment by aayanl** [comment]
# Suicidal PROP
-------

Every defined units of time (hours, days, weeks), drop EVERY share making pool hoppers earn nothing.

**Comment by aayanl** [comment]
Would love to know some opinions before I code it :)

**Comment by hellcatz** [comment]
The defined amount of time would need to be chosen carefully based on the pool's actual block interval. If it takes a few days to find a block, then suicidal dropping of the shares wouldn't hurt a new miner but it would remove the potential pool hoppers shares. This seems like a good addition to PPLT and/or PROP.

**Comment by fittsy** [comment]
Maybe for established pools but for those of us struggling to build a userbase I don't think we could. We need to appeal to more miners not less.

**Comment by aayanl** [comment]
I was thinking I would just put in `suicidal` in pools_config and how often per day it should reset the shares. 0 being never and the default.

**Comment by setvir** [comment]
Agree with fittsy once the pool has grown... Chasing away larger miners as they would not want to stake their hashing power when they lose so much...

**Comment by isaev8871** [comment]
PPLS and Pay Per Block (only how find block get all reward)

**Comment by SongZhizhai** [comment]
How to use PPS (pay per share) mode?

**Comment by mooleshacat** [comment]
@SongZhizhai 
> How to use PPS (pay per share) mode?

The documentation may not be clear enough (suggestion to z-nomp devs) there is a fix for that at the bottom :P

**Edit pool_configs/*.json and add in:**
```
        "paymentMode": "pplnt",
        "pplnt": 0.51,
```

**Or use [EasyNOMP](https://github.com/leshacat/EasyNOMP) and wait for [this issue](https://github.com/leshacat/EasyNOMP/issues/134) to complete.**
