### ISSUE TITLE
I started it 47.93.44.197:5959  But mine is not connected pool

### ISSUE THREAD

**Issue by wuhuaping** [z-classic/z-nomp#136]
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp# npm start

> z-nomp@0.0.4 start /root/z-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

2017-05-08 19:44:56 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2017-05-08 19:44:56 [Master]	[CLI] CLI listening on port 17117
2017-05-08 19:44:56 [Master]	[PoolSpawner] Spawned 1 pool(s) on 2 thread(s)
2017-05-08 19:44:56 [Payments]	[zclassic] zclassic requireShielding: true
2017-05-08 19:44:56 [Payments]	[zclassic] zclassic payments txfee reserve: 0.0004
2017-05-08 19:44:56 [Payments]	[zclassic] zclassic maxBlocksPerPayment: 3
2017-05-08 19:44:56 [Website]	[Server] Website started on 0.0.0.0:5959
2017-05-08 19:44:56 [Payments]	[zclassic] Payment processing setup to run every 20 second(s) with daemon (friend@127.0.0.1:18133) and redis (127.0.0.1:6379)
2017-05-08 19:44:57 [Payments]	[zclassic] Finished interval - time spent: 23ms total, 15ms redis, 18ms daemon RPC
2017-05-08 19:44:57 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 1) No rewardRecipients have been setup which means no fees will be taken
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 1) p2p connection successful
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 1) Stratum Pool Server Started for zclassic [ZCL] {equihash}
						Network Connected:	Mainnet
						Detected Reward Type:	POW
						Current Block Height:	104147
						Current Block Diff:	110708.229937203
						Current Connect Peers:	47
						Network Difficulty:	109934.4189257936
						Network Hash Rate:	5.44 MH
						Stratum Port(s):	8888
						Pool Fee Percent:	0%
						Block polling every:	500 ms
2017-05-08 19:44:57 [Switching]	[Setup] (equihash) Setting proxy difficulties after pool start
2017-05-08 19:44:57 [Switching]	[Setup] (Thread 2) Loading last proxy state from redis
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 2) No rewardRecipients have been setup which means no fees will be taken
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 2) Stratum Pool Server Started for zclassic [ZCL] {equihash}
2017-05-08 19:44:57 [Switching]	[Setup] (equihash) Setting proxy difficulties after pool start
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 2) p2p connection successful
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 2) Block notification via p2p
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 1) Block notification via p2p
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 1) Block notification via blocknotify script
2017-05-08 19:44:57 [Pool]	[zclassic] (Thread 2) Block notification via blocknotify script

Who can help me solve it
 290756156@qq.com

**Comment by wuhuaping** [comment]
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp# ls
CHANGELOG.md  coins  config_example.json  config.json  init.js	libs  LICENSE  node_modules  package.json  pool_configs  README.md  scripts  website
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp# cd node_modules/
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp/node_modules# ls
abbrev		     bs58		      destroy		  hoek			   minimatch		 proxy-addr	   stringstream
accepts		     bs58check		      dot		  http-errors		   minimist		 punycode	   string-width
ajv		     buffer-shims	      double-ended-queue  http-signature	   mkdirp		 pushdata-bitcoin  strip-ansi
ansi-regex	     bytes		      ecc-jsbn		  iconv-lite		   ms			 qs		   strip-json-comments
aproba		     caseless		      ecurve		  inflight		   mysql		 randombytes	   tar
are-we-there-yet     cipher-base	      ee-first		  inherits		   nan			 range-parser	   tar-pack
array-flatten	     co			      encodeurl		  ini			   negotiator		 raw-body	   tough-cookie
asap		     code-point-at	      equihashverify	  ipaddr.js		   node-gyp		 rc		   tunnel-agent
asn1		     colors		      escape-html	  isarray		   node-json-minify	 readable-stream   tweetnacl
assert-plus	     combined-stream	      etag		  isexe			   node-pre-gyp		 redis		   typeforce
async		     compressible	      express		  is-fullwidth-code-point  node-watch		 redis-commands    type-is
asynckit	     compression	      extend		  isstream		   nonce		 redis-parser	   uid-number
aws4		     concat-map		      extsprintf	  is-typedarray		   nopt			 request	   unpipe
aws-sign2	     console-control-strings  finalhandler	  jodid25519		   npmlog		 rimraf		   util-deprecate
balanced-match	     content-disposition      forever-agent	  jsbn			   number-is-nan	 ripemd160	   utils-merge
base58-native	     content-type	      form-data		  jsonify		   oauth-sign		 safe-buffer	   uuid
base-x		     cookie		      forwarded		  json-schema		   object-assign	 semver		   varuint-bitcoin
bcrypt-pbkdf	     cookie-signature	      fresh		  json-stable-stringify    once			 send		   vary
bigi		     core-util-is	      fs.realpath	  json-stringify-safe	   on-finished		 serve-static	   verror
bignum		     create-hash	      fstream		  jsprim		   on-headers		 set-blocking	   which
bignumber.js	     create-hmac	      fstream-ignore	  lodash		   osenv		 setprototypeof    wide-align
bindings	     cryptiles		      gauge		  media-typer		   os-homedir		 sha.js		   wif
bip66		     dashdash		      getpass		  merge-descriptors	   os-tmpdir		 signal-exit	   wrappy
bitcoinjs-lib-zcash  dateformat		      glob		  merkle-bitcoin	   parseurl		 sntp
bitcoin-ops	     debug		      graceful-fs	  merkle-lib		   path-is-absolute	 sqlstring
block-stream	     deep-extend	      har-schema	  methods		   path-to-regexp	 sshpk
body-parser	     delayed-stream	      har-validator	  mime			   performance-now	 statuses
boom		     delegates		      has-unicode	  mime-db		   process-nextick-args  stratum-pool
brace-expansion      depd		      hawk		  mime-types		   promise		 string_decoder
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp/node_modules# cd stratum-pool/
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp/node_modules/stratum-pool# ls
lib  LICENSE  node_modules  package.json  README.md
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp/node_modules/stratum-pool#

**Comment by hellcatz** [comment]
http://47.93.44.197:5959/   is working here....

If the pool server is running on the same source of Internet as your PC, you may need to use your local IP vs public IP.  It has something to do with NAT Loopback not working in your LAN (not a big deal).

You can always test from a second source of Internet.

**Comment by wuhuaping** [comment]
@hellcatz 
I use public IP

**Comment by wuhuaping** [comment]
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp/pool_configs# vi zclassic.json 

{
    "enabled": true,
    "coin": "zclassic.json",

    "address": "t1PxThHFVwJtf7uMty5z2Xw1hhKoqFy28QV",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "zcHS134HQmbQXABLKBjBZnvThWYHBf7d2b534z7sYizPGtBfCWakYhpsbUx6mWL6JvXET57qR1H7QF1NTHoNYcAsEGp6f6g",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "t1PdK9S65hs79Q8vKWN1JNGkWsECtTqYzNa",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "walletInterval": 2.5,

    "rewardRecipients": {
    },

    "tlsOptions": {
        "enabled": false,
        "serverKey":"",
        "serverCert":"",
        "ca":""
    },

    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 20,
        "minimumPayment": 0.1,
        "maxBlocksPerPayment": 3,
        "daemon": {
            "host": "127.0.0.1",
            "port": 18133,
            "user": "friend",
            "password": "chang"
        }
    },

    "ports": {
        "8888": {
            "tls":true,
            "diff": 0.05,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 18133,
            "user": "friend",
            "password": "chang"
        }
    ],

    "p2p": {
        "enabled": true,
        "host": "127.0.0.1",
        "port": 8133,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "zcl",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}

**Comment by wuhuaping** [comment]
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp# vi config.json 

{
    "logLevel": "debug",
    "logColors": true,

    "cliPort": 17117,

    "clustering": {
        "enabled": true,
        "forks": "auto"
    },

    "defaultPoolConfigs": {
        "blockRefreshInterval": 500,
        "jobRebroadcastTimeout": 55,
        "connectionTimeout": 600,
        "emitInvalidBlockHashes": false,
        "validateWorkerUsername": true,
        "tcpProxyProtocol": false,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 500,
            "purgeInterval": 300
        },
        "redis": {
            "host": "127.0.0.1",
            "port": 6379
        }
    },

    "website": {
        "enabled": true,
        "host": "0.0.0.0",
        "port": 5959,
        "stratumHost": "47.93.44.197",
        "stats": {
            "updateInterval": 30,
            "historicalRetention": 14400,
            "hashrateWindow": 300
        },
        "adminCenter": {
            "enabled": false,
            "password": "password"
        },
        "tlsOptions" : {
            "enabled": false,
            "cert": "",
            "key": ""
        }
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "switching": {
        "switch1": {
            "enabled": false,
            "algorithm": "sha256",
            "ports": {
                "3333": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch2": {
            "enabled": false,
            "algorithm": "scrypt",
            "ports": {
                "4444": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch3": {
            "enabled": false,
            "algorithm": "x11",
            "ports": {
                "5555": {
                    "diff": 0.001,
                    "varDiff": {
                        "minDiff": 0.001,
                        "maxDiff": 1,
                        "targetTime": 15,
                        "retargetTime": 60,
                        "variancePercent": 30
                    }
                }
            }
        }
    },

    "profitSwitch": {
        "enabled": false,
        "updateInterval": 600,
        "depth": 0.90,
        "usePoloniex": true,
        "useCryptsy": true,
        "useMintpal": true,
        "useBittrex": true
    }
}

**Comment by wuhuaping** [comment]
{
    "name": "zclassic",
    "symbol": "zcl",
    "algorithm": "equihash",
    "requireShielding": true,
    "peerMagic": "24e92764",
    "txfee": 0.0004
}

**Comment by wuhuaping** [comment]
root@iZ2zegquegjgaxid7pimbwZ:~/z-nomp/node_modules/stratum-pool# ls
lib  LICENSE  node_modules  package.json  README.md

**Comment by wuhuaping** [comment]
tcp6       0      0 :::8333                 :::*                    LISTEN      24353/litecoind 
tcp6       0      0 :::9999                 :::*                    LISTEN      3631/node       
tcp6       0      0 :::8080                 :::*                    LISTEN      3631/node       
tcp6       0      0 :::8888                 :::*                    LISTEN      5906/node       
tcp6       0      0 :::25                   :::*                    LISTEN      1093/master     
tcp6       0      0 :::8133                 :::*                    LISTEN      1003/zcashd     
udp        0      0 127.0.0.1:11211         0.0.0.0:*                           576/memcached   
udp        0      0 0.0.0.0:10000           0.0.0.0:*                           907/perl        
udp        0      0 172.17.188.3:123        0.0.0.0:*                           704/ntpd        
udp        0      0 127.0.0.1:123           0.0.0.0:*                           704/ntpd        
udp        0      0 0.0.0.0:123             0.0.0.0:*                           704/ntpd        
udp6       0      0 :::123                  :::*                                704/ntpd

**Comment by aayanl** [comment]
Seems to be an issue with the machine and not z-nomp, closing but I'm happy to help

**Comment by aayanl** [comment]
make sure the stratum ports aren't firewalled

**Comment by wuhuaping** [comment]
Yes, no firewall has been opened
It is closed

**Comment by wuhuaping** [comment]
@aayanl   Thank you
Please take a look at it if you solve it
It should be the same if you try to build
Or because of algorithmic errors?

**Comment by wuhuaping** [comment]
如果您能协助或帮我我解决它我将捐赠您2 LTC    邮箱 290756156@qq.com 


发送自我的三星 Galaxy 智能手机。
-------- 原始信息 --------由： Procrastinator <notifications@github.com> 日期: 17/5/12  05:25  (GMT+08:00) 收件人： z-classic/z-nomp <z-nomp@noreply.github.com> 抄送： Q290756156 <atiger7758@163.com>, Author <author@noreply.github.com> 主题： Re: [z-classic/z-nomp] I started it 47.93.44.197:5959 But mine is not connected pool (#136) 
make sure the stratum ports aren't firewalled

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/z-classic/z-nomp","title":"z-classic/z-nomp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/z-classic/z-nomp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aayanl in #136: make sure the stratum ports aren't firewalled"}],"action":{"name":"View Issue","url":"https://github.com/z-classic/z-nomp/issues/136#issuecomment-300921443"}}}
