### ISSUE TITLE
ZCash difficulty settings.

### ISSUE THREAD

**Issue by Xandrah** [z-classic/z-nomp#137]
I am most likely not posting in the correct section, but how do I set a fixed default difficulty without vardiff changing it? I was to set my pool at a default of 2000 difficulty.

**Comment by aayanl** [comment]
just remove the vardiff part on the port, also if you're aiming for a network diff of 2000, you would have to divide it by 8192 because with z-nomp, 1 diff is actually 8192. So set it to 0.244140625

**Comment by Xandrah** [comment]
Thank you for the quick response!

**Comment by mxbdev** [comment]
Thank you too. This solves the mystery and I can tune my znomp.
