### ISSUE TITLE
No Zcash Network Stats

### ISSUE THREAD

**Issue by RecoStar** [z-classic/z-nomp#145]
Hey everyone, this is most likely not an issue and more likely me being a noob lol.

I have set up my z-nomp mining pool and everything is working great (thanks for creating this!), but on the "Graph Stats" no "Zcash Network Stats" are being displayed. Any ideas to this? I've search around and cant seem to find a solution to this.

My miners are mining Zcash, but the .json being used is zclassic.json, is that correct? This is however pointing to "coin": "zcash.json",

I dont have p2p enabled as not sure on how to set it up. Enabled it before then edited the zclassic.json to have "peerMagic": "fbc0b6db", but just got a lot of errors when trying to run npm.

Also is their a command to check what block your pool / miners are currently working on?

Thanks in advance,

Stu

**Comment by RecoStar** [comment]
Anyone have any ideas?

**Comment by aayanl** [comment]
On your pool_config, set coin to zcash.json

**Comment by RecoStar** [comment]
Thanks :)
