### ISSUE TITLE
Shielding can get stuck; SendTToZ / SendZToT is waiting...

### ISSUE THREAD

**Issue by hellcatz** [z-classic/z-nomp#146]
Sometimes (mostly with hush coin) shielding coins gets stuck and shows `SendTToZ / SendZToT is waiting...` messages when there actually is no pending `z_sendmany` operations. This can lead to pending blocks never paying and confirmations just keep counting up...

It requires restarting z-nomp to clear the internal `opidCount` variable to resume normal pool operations.

**Comment by hellcatz** [comment]
It was discovered this problem can occur when `paymentInterval` is set too low in your pool_config.
Short `paymentInterval` can result in overloading the RPC work queue leading to paymentProcessor problems. It is recommended to have a `paymentInterval` no less than 3 minutes.

**Comment by aayanl** [comment]
utACK

**Comment by sonicdx10** [comment]
PaymentInterval is bases on secs right? so it needs more than 180 right?

**Comment by aayanl** [comment]
PaymentInterval is in seconds, walletInterval is in minutes

**Comment by aayanl** [comment]
if you're pushing tons of blocks every few minutes, it's best to delay payments to once every 30 minutes or so. Maybe even twice a day

**Comment by Kosta85** [comment]
In my config payment interval set to 180, the problem with zen presist
