### ISSUE TITLE
Invalid or unsupported block header version

### ISSUE THREAD

**Issue by swarkn** [z-classic/z-nomp#148]
Hi guys,

First of all let me say thank you for building and maintaining z-nomp! :)

I want to support zencash for my private mining pool in the future. So i set up a testnet wallet and the latest branch of z-nomp inkl. the zen prep (sennevb-patch-1). If i try to mine against the pool, i get the following error message from my miner:
```
[18:20:30][0x00001d30] stratum | Received: {"id":null,"method":"mining.notify","params":["ccce","00000020","c63c294c9e78f0149a96a7b8d217d88b5ca4fb7117ea2c9f38095f86ae130000","844ee722aa698ab79d3ddce51abf77b7befc737efad4dc76eac88d706fcc3192","0000000000000000000000000000000000000000000000000000000000000000","21032759","2d867f1e",true]}
[18:20:30][0x00001d30] stratum | ZcashMiner::parseJob(): Invalid or unsupported block header version
[18:20:30][0x00001d30] stratum | Reconnecting in 3 seconds...
```
This message does also appear using the master branch or the zen prep branch. Is mining with z-nomp not allowed/possible in testnet or did i miss something? I am using "Windows_x64_nheqminer-5c" as my testminer app.

Thank you very much for looking into this. :)

- Stefan

**Comment by sennevb** [comment]
This has nothing to do with z-nomp. To use zen you need modified nhegminer. Aayanl has a build somewhere on github

**Comment by aayanl** [comment]
We've softforked bip9 into zencash which nheqminer isn't too happy about. I've submitted a fix to nicehash but yet to get a response, till then you can build your own version here https://github.com/aayanl/nheqminer

**Comment by swarkn** [comment]
I tried building and everything worked perfectly. Thank you very much! 👍

**Comment by toni-mahoni** [comment]
hi aayanl,

 i try to mine the new btcp with this miningsoft but with the same errormessage:
parseJob(): Invalid or unsupported block header version

i have never made a build - to your reportet fix - is there any miningsoftware availeble with a fix of this error?

cheers
