### ISSUE TITLE
Work queue depth exceeded

### ISSUE THREAD

**Issue by hellcatz** [z-classic/z-nomp#151]
This is not an issue but to help document how to overcome `Work queue depth exceeded` coin daemon errors. Running into this error may lead to other random issues as the coin daemon is not responding properly to expected RPC calls.

This error will happen when your coin daemon is too busy processing a backlog of RPC calls.
To help reduce the amount of RPC calls to your coin daemon (not all may apply):

 * Increase blockRefreshInterval in config.json or set to 0 and use block notify scripts
 `"blockRefreshInterval": 0,` use block notify scripts (note setup your coin daemon config!)
 `blocknotify=node /home/user/z-nomp/scripts/cli.js blocknotify zclassic %s`

 * Increase paymentInterval in pool_config
 `"paymentInterval": 600,`  10 minute intervals

 * Increase walletInterval in pool_config
 `"walletInterval": 5,` 5 minute intervals

 * Increase RPC work queue depth in coin daemon config
 `rpcworkqueue=64`

The above settings are examples only.

**Comment by sonicdx10** [comment]
Examples but they work for you, right? So as it is, is ok? Working just fine with those values?

**Comment by hellcatz** [comment]
Those values have been gathered from the community with various configurations. Your mileage may vary.
