### ISSUE TITLE
Whether you can add payment lists and market prices.

### ISSUE THREAD

**Issue by ceozero** [z-classic/z-nomp#152]
Whether you can add payment lists and market prices.

like this http://luckpool.org/payments

**Comment by hellcatz** [comment]
Untested commits to look at...

https://github.com/hellcatz/z-nomp/commit/1df375e9d101112eb8ce95d0c7b69de3fc0f7d3c
https://github.com/hellcatz/z-nomp/commit/214856def84fba98a835a680cf8b9c275c6efb65

**Comment by ceozero** [comment]
![image](https://cloud.githubusercontent.com/assets/22513657/26762184/550ab8f4-4970-11e7-8a07-df06ebc40804.png)
@hellcatz  is not good....

**Comment by sennevb** [comment]
you need to do a bit of styling on your table i guess..
