### ISSUE TITLE
Error with RPC call z_getoperationstatus {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}

### ISSUE THREAD

**Issue by liudongjia** [z-classic/z-nomp#154]
Error with RPC call z_getoperationstatus {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:19332"}

**Comment by mckenzieja** [comment]
I'd check to see if your coin daemon is running on that port?

**Comment by glasswool** [comment]
Hi Joshua, please could you share share what the contents of the following files, once properly configured look like:
1) daemon zcash.conf 
2) poolconfig/zcash.conf 
3) z-nomp/config.json
Thanks
Orlando
