### ISSUE TITLE
Not an issue but info - Call to Developers

### ISSUE THREAD

**Issue by krisklosterman** [z-classic/z-nomp#163]
I know this is a nomp fork. But I am looking to improve nomp base and would like any development help that I can get.

Here is a slack channel made around NOMP

https://join.slack.com/nomp/shared_invite/MjA5Nzk0MzE2NDcwLTE0OTkzNjY3NTMtMTc5ODY1OTQ5OA

**Comment by sennevb** [comment]
link no longer active...

**Comment by krisklosterman** [comment]
@sennevb Added new link
