### ISSUE TITLE
payment issue

### ISSUE THREAD

**Issue by PePPeRmix** [z-classic/z-nomp#168]
hello, every time i got payment issue like this one
2017-07-19 11:00:36 [Payments]      [hush] Insufficient funds (0.00259442) to process payments (12.49980225) for 1 blocks; possibly waiting for txs.
hush-cli getwalletinfo
{
  "walletversion": 60000,
  "balance": 0.00259442,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 12.50030000,
  "txcount": 138,
  "keypoololdest": 1499707009,
  "keypoolsize": 101,
  "paytxfee": 0.00000000
}
hush-cli listunspent
[
  {
    "txid": "d281fd212b3396c8f7bb56dfe817b7f19515cfcb58ab8d6270964a59974c4429",
    "vout": 0,
    "address": "t1WrJucfj3ySefztzjY3dhARKGDu6HcQjy6",
    "scriptPubKey": "76a9148e5af22e64e4ce8d03b8d6a43daff513146408f688ac",
    "amount": 0.00259442,
    "confirmations": 731,
    "spendable": true
  }
]
![10](https://user-images.githubusercontent.com/584055/28356825-10189e94-6c72-11e7-9039-ac7930c3826b.PNG)

**Comment by Tmotta** [comment]
Mine does the same exact thing, Payments do finally go through at about 140-150 confirms. But it does not show it is sheilding.

**Comment by PePPeRmix** [comment]
2017-07-19 15:53:04 [Payments]      [hush] Insufficient funds (0.00259442) to process payments (24.99970225) for 2 blocks; possibly waiting for txs.
hush-cli listunspent
[
  {
    "txid": "d281fd212b3396c8f7bb56dfe817b7f19515cfcb58ab8d6270964a59974c4429",
    "vout": 0,
    "address": "t1WrJucfj3ySefztzjY3dhARKGDu6HcQjy6",
    "scriptPubKey": "76a9148e5af22e64e4ce8d03b8d6a43daff513146408f688ac",
    "amount": 0.00259442,
    "confirmations": 841,
    "spendable": true
  },
  {
    "txid": "04af7a196171b43ac03e9ae29ec6087b370b6668bcddf0c79335376d6a60206a",
    "vout": 0,
    "address": "t1Pd626U121hzHCT7VtGZBLVXSmvFgTDW35",
    "account": "",
    "scriptPubKey": "76a9143f11e64100b775c8e2694ce7782151b325cf3bad88ac",
    "amount": 12.50000225,
    "confirmations": 58,
    "spendable": true
  },
  {
    "txid": "1cf0980ab8b91fce88f39bacf8cbeba062e1fc8b1b720dfe1d7cfb5273fcc3e3",
    "vout": 0,
    "address": "t1Pd626U121hzHCT7VtGZBLVXSmvFgTDW35",
    "account": "",
    "scriptPubKey": "76a9143f11e64100b775c8e2694ce7782151b325cf3bad88ac",
    "amount": 12.50000225,
    "confirmations": 57,
    "spendable": true
  }
]
hush-cli getwalletinfo
{
  "walletversion": 60000,
  "balance": 25.00259892,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 141,
  "keypoololdest": 1499707009,
  "keypoolsize": 101,
  "paytxfee": 0.00000000
}
![10](https://user-images.githubusercontent.com/584055/28367726-a4c10d4c-6c9a-11e7-9f2c-06db38322866.PNG)

**Comment by madbuda** [comment]
@Tmotta I would guess yours is due to blocks per transaction. Default it 3, so if you have 1 block nearing payment and a new block matures neither will payout until the 2nd block is matured. Default being 3 you could have up to 3 blocks waiting to be paid

**Comment by Tmotta** [comment]
@madbuda is there something I can do that shows the block as sheilding? I thought it was supposed to Show on webpage stats it was sheilding like it shows paid?

**Comment by madbuda** [comment]
@Tmotta the blocks show on the graph stats page with red text and the number of confirmations they have.

Possibly do some math based on how many blocks you pay together and how close each immature block is?? you can source the data from `it.stats.pools[pool].pending.confirms`

**Comment by PePPeRmix** [comment]
i set it to 1 block per payment right now, and still got same issue.
2017-07-20 08:32:11 [Payments]      [hush] Insufficient funds (0.00289124) to process payments (12.50005144) for 1 blocks; possibly waiting for txs.
hush-cli listunspent
[
  {
    "txid": "d281fd212b3396c8f7bb56dfe817b7f19515cfcb58ab8d6270964a59974c4429",
    "vout": 0,
    "address": "t1WrJucfj3ySefztzjY3dhARKGDu6HcQjy6",
    "scriptPubKey": "76a9148e5af22e64e4ce8d03b8d6a43daff513146408f688ac",
    "amount": 0.00259442,
    "confirmations": 1239,
    "spendable": true
  },
  {
    "txid": "85d588e051387d980ce969a84de24dcc15d13fbbfd81977fd85d8b86bc09e469",
    "vout": 2,
    "address": "t1Pcvk4ZueZZqnn2KEWUTdKupi16SPCn6To",
    "scriptPubKey": "76a9143f0a27e659f6802dc8b87d3cb51f46fa1c3f587f88ac",
    "amount": 0.00029682,
    "confirmations": 351,
    "spendable": true
  }
]
hush-cli getwalletinfo
{
  "walletversion": 60000,
  "balance": 0.00289124,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 144,
  "keypoololdest": 1499707009,
  "keypoolsize": 101,
  "paytxfee": 0.00000000
}
![10](https://user-images.githubusercontent.com/584055/28402033-42d7109a-6d26-11e7-9c63-3c3b6f80da2b.PNG)

**Comment by sennevb** [comment]
What does z_gettotalbalance return?

**Comment by PePPeRmix** [comment]
{
  "transparent": "0.00289124",
  "private": "12.50014919",
  "total": "12.50304043"
}

**Comment by sennevb** [comment]
Funds are in your private wallet... DID you change z address or so?

**Comment by PePPeRmix** [comment]
nope, it's just happen... 3 days works fine, and after i get issue, nothing changes, after N reloads z-nomp it can be fixed, but next block again same thing.
idk, maybe issue couse i got 32threads(2xE5 processors)

**Comment by sennevb** [comment]
Are you waiting long enough for the shielding transaction, it takes time..

Try rpcqueuesize = 128 in your coins hush.conf and try again

**Comment by PePPeRmix** [comment]
ok, looks like it solved, but might be not....
unshielding started.
can i not use shielding? because by default it was turned on, i didn't change it.

**Comment by sennevb** [comment]
You cannot. Nice server you have :-)

**Comment by PePPeRmix** [comment]
oooh, it's not solved, after unshielding i get same error
Insufficient funds (0.00289124) to process payments (12.50005144) for 1 blocks; possibly waiting for txs.
getwalletinfo
{
  "walletversion": 60000,
  "balance": 12.50294043,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 145,
  "keypoololdest": 1499707009,
  "keypoolsize": 101,
  "paytxfee": 0.00000000
}
listunspent
[
  {
    "txid": "d281fd212b3396c8f7bb56dfe817b7f19515cfcb58ab8d6270964a59974c4429",
    "vout": 0,
    "address": "t1WrJucfj3ySefztzjY3dhARKGDu6HcQjy6",
    "scriptPubKey": "76a9148e5af22e64e4ce8d03b8d6a43daff513146408f688ac",
    "amount": 0.00259442,
    "confirmations": 1294,
    "spendable": true
  },
  {
    "txid": "85d588e051387d980ce969a84de24dcc15d13fbbfd81977fd85d8b86bc09e469",
    "vout": 2,
    "address": "t1Pcvk4ZueZZqnn2KEWUTdKupi16SPCn6To",
    "scriptPubKey": "76a9143f0a27e659f6802dc8b87d3cb51f46fa1c3f587f88ac",
    "amount": 0.00029682,
    "confirmations": 406,
    "spendable": true
  },
  {
    "txid": "fc5054349325ef638c77dfee06a6af82b952d467e086b5ef41932b68eb59ffc5",
    "vout": 0,
    "address": "t1Pd626U121hzHCT7VtGZBLVXSmvFgTDW35",
    "account": "",
    "scriptPubKey": "76a9143f11e64100b775c8e2694ce7782151b325cf3bad88ac",
    "amount": 12.50004919,
    "confirmations": 6,
    "spendable": true
  }
]

**Comment by sennevb** [comment]
How long do you wait when you see this??

**Comment by PePPeRmix** [comment]
~10-20min.
payment every 10min.
still got same issue

**Comment by PePPeRmix** [comment]
afte i mannualy spend this amount, all works fine, but  it's not autopayment at all

**Comment by PePPeRmix** [comment]
Insufficient funds (0) to process payments (12.50005144) for 1 blocks; possibly waiting for txs.

**Comment by sennevb** [comment]
Weird, have TeamViewer or so, pm me credentials

**Comment by PePPeRmix** [comment]
ok, i check src, and find command for listunspent, it must be  listunspent 100 99999
and return this
[
]
because this transactions didn't get 100 confirmations

**Comment by PePPeRmix** [comment]
Thanks, to all, i found fix.
in pool config minConf must be 10, it was 100
"paymentProcessing": {
        "minConf": 10,

**Comment by przemekh10** [comment]
I have "minConf" set to 10. Block was mined yesterday and still is "pending". I have these errors:

1. [Payments] [zclassic] Shield balance 12.4134
2. [Payments] [zclassic] Insufficient funds (0) to process payments (12.4131) for 1 blocks; possibly waiting for txs.
3. [Payments] [zclassic] Error trying to send z_address coin balance to payout t_address.{"code":3,"message":"Amount is not a number or string"}
4. [Payments] [zclassic] Error trying to shield balance Nan {"code":-3,"message":"Amount is not a number or string"}

I have checked balances with zcash-cli:
- address: 12.41350000
- zAddress: 0
- tAddress: 0

**Comment by Tomas-M** [comment]
I am having similar issue.

    zcash-cli z_gettotalbalance
    {
      "transparent": "1852.65500519",
      "private": "11275.24218136",
      "total": "13127.89718655"
    }

But still, Insufficient funds (25.82018425) to process payments (377.86358563); possibly waiting for txs.

**Comment by madbuda** [comment]
sounds like you have the coin configured wrong, possibly using the same t_address for address and t_address in pool_config/coin.json

**Comment by vtnplus** [comment]
I have error 
`Insufficlient founds (......) to process payment (......); Possibly waiting for txs`
What i need do fix :(

**Comment by Tomas-M** [comment]
Basically the error Insufficient funds is not an error. It's just a notice that currently there are not enough funds matured+shielded+unshielded to send payment for the last block(s), but this will fix itself.

I think the error message should be removed from z-nomp or at least it should be marked with different color, not red. Most of the misunderstanding about this is that people do not get that for each mined block, they have to wait 
- 100 blocks for maturing 
- 10 more blocks to confirm shielding
- 10 more blocks to confirm unshielding
- and wait until 3 last found blocks are confirmed this way.

Only then the payment can be sent to miners.

If the server has slow hardware, the shielding and unshielding takes very long time to execute, delaying this even further.

**Comment by jcreyesb** [comment]
i am deploying bitcoinz pool and my config:
Coin:
{
"name": "Bitcoinz",
"symbol": "btcz",
"algorithm": "equihash",
"requireShielding": true,
"txfee": 0.0001

}

pool:
`"coin": "bitcoinz.json",

"coin": "bitcoinz.json",

"address": "t1PPKiaskZsSXZb.....",
"_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

"zAddress": "zcNus9QdXx3skhE5KzQx9.......
"_comment_zAddress": "a private address used to send coins to tAddress.",

"tAddress": "t1JrZXDy5N......",
"_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

"walletInterval": 2.5,

"rewardRecipients": {
    "t1diyf84HoFYztg.....":1.5
},

"tlsOptions": {
    "enabled": false,
    "serverKey":"",
    "serverCert":"",
},

"paymentProcessing": {
    "minConf": 10,
    "enabled": true,
    "paymentMode": "prop",
    "_comment_paymentMode":"prop, pplnt",
    "paymentInterval": 20,
    "minimumPayment": 100,
    "maxBlocksPerPayment": 1,
    "daemon": {
        "host": "127.0.0.1",
        "port": 3333,
        "user": "xxxx",
        "password": "xxx"
    }
},`
but always show the error

017-10-07 04:50:39 [Payments] [bitcoinz] Insufficient funds (0) to process payments (12312.5); possibly waiting for txs.

my balance
ubuntu@ip-172-31-34-70:~/bitcoinz-pkg$ ./zcash-cli z_gettotalbalance
{
"transparent": "12312.5001",
"private": "0.00",
"total": "12312.5001"
}

**Comment by madbuda** [comment]
@jcreyesb this issues is closed, if you are having problems please open your own issue

**Comment by lokko82** [comment]
@madbuda thanks for info :)
I had the same problems
after which I "maxBlocksPerPayment": 3,
set to 1, the matter was done

**Comment by savskii** [comment]
hello guys, cam anyone help me with this problem on my Hush pool

[Pool]      [hush] (Thread 4) Share rejected: {"job":"cccd","ip":"::ffff:31.24.216.135","worker":"t1aPXQqsm9fFZzhFotsYeJyvve3SNgURCQH.Rig18","difficulty":2.4,"error":"incorrect size of solution"}

Thanks in advance

**Comment by madbuda** [comment]
The miner isn’t submitting correct solutions... this happens with a bad
miner or when someone is trying to spoof a real miner.

I’d suggest you post an issue on znomp regarding this
