### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tecnoinfoch** [z-classic/z-nomp#173]
I followed your instructions (https://zdeveloper.org/wiki:z-nomp_install#downloading_installing)and the command npm install generate this error:

root@pool01:/home/pool/zcash/znomp# npm install

> bignum@0.12.5 install /home/pool/zcash/znomp/node_modules/bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v51-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@7.10.1 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pool/zcash/znomp/node_modules/bignum/.node-gyp"
make: ingresso nella directory "/home/pool/zcash/znomp/node_modules/bignum/build"
make: ***  Nessuna regola per generare l'obiettivo "../.node-gyp/7.10.1/include/node/common.gypi", necessario per "Makefile".  Arresto.
make: uscita dalla directory "/home/pool/zcash/znomp/node_modules/bignum/build"
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pool/zcash/znomp/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.0-59-generic
gyp ERR! command "/usr/bin/nodejs" "/home/pool/zcash/znomp/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pool/zcash/znomp/node_modules/bignum/binding/bignum.node" "--module_name=bignum" "--module_path=/home/pool/zcash/znomp/node_modules/bignum/binding"
gyp ERR! cwd /home/pool/zcash/znomp/node_modules/bignum
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/pool/zcash/znomp/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pool/zcash/znomp/node_modules/bignum/binding/bignum.node --module_name=bignum --module_path=/home/pool/zcash/znomp/node_modules/bignum/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pool/zcash/znomp/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.8.0-59-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/pool/zcash/znomp/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pool/zcash/znomp/node_modules/bignum
node-pre-gyp ERR! node -v v7.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs /home/pool/zcash/znomp/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pool/zcash/znomp/node_modules/bignum/binding/bignum.node --module_name=bignum --module_path=/home/pool/zcash/znomp/node_modules/bignum/binding' (1)
npm ERR! Linux 4.8.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-08-03T13_51_53_035Z-debug.log

you have a solution?

**Comment by tecnoinfoch** [comment]
solved 

git clone git://github.com/justmoon/node-bignum.git
cd node-bignum
npm install

**Comment by mrsaicharan1** [comment]
Hey. I'm still getting the same error when I did the aforementioned steps! Could you help me out? How did it get resolved?

**Comment by RealAwesomeness** [comment]
Do it in node_modules directory,
