### ISSUE TITLE
payment mode

### ISSUE THREAD

**Issue by isaev8871** [z-classic/z-nomp#180]
please help, maybe script.. i have several miners whith different addresses on pool. And need thats all reward fo block paying that miner who find block (-% comiss). How solo, only for several miners....

**Comment by isaev8871** [comment]
elso question), which var show all count blocks by worker?

**Comment by madbuda** [comment]
@isaev8871  https://github.com/z-classic/z-nomp/blob/master/libs/stats.js

It's not clear what you are asking, but this would be the place to start if you want
