### ISSUE TITLE
Improve Invalid Address Handling

### ISSUE THREAD

**Issue by hellcatz** [z-classic/z-nomp#181]
Sometimes invalid "short" and "long" address earn shares and break payment system.

Proposed fix will prevent payment system from breaking on "short" or "long" address.
Proposed fix will send earned shares from invalid address to address specified in pool config.
This will prevent funds being lost from shares earned by invalid addresses.
They are treated as a donation to the pool itself.

Bounty Requested of (10 ZEN or 45 HUSH) or equal combination of the two (~0.015 BTC)
Bounty Address ZEN: zndFf7exGvKMpXwcJUuRuCjgaLC9NgudkK7
Bounty Address HUSH: t1gQkQ1rtWyYu4ZfnSt4MRGtQ6XDq6Dh6T3

**Comment by sennevb** [comment]
interested!! willing to pay an amount of the bounty, but looking for other people to cooperate to get the 20 ZEN..

**Comment by madbuda** [comment]
I'll pitch in 20 hush

**Comment by aayanl** [comment]
https://explorer.zensystem.io/tx/6754e92dac4cd3955c5349320bfe1f166cffd3bd4ba87f83599fd157fd0f199a 5 zen

**Comment by aayanl** [comment]
that should be 0.016 total for current market prices for hush and zen :)

**Comment by sennevb** [comment]
i'll add an additional 15 hush
https://explorer.myhush.org/tx/09b819ea25fc22ff794eae6bf40785ef649943f009cdf63b37ab027c6c6b9209

**Comment by hellcatz** [comment]
Adding to this current PR, thank you for support!
https://github.com/z-classic/z-nomp/pull/179

**Comment by madbuda** [comment]
hushpool.cloud
[10:40 AM] 
hi @hellcatz my little support for your work on this issue https://github.com/z-classic/z-nomp/issues/181
https://explorer.myhush.org/tx/97887ae247d7ec633efb0761b6f14546ab7a7944d0f96c08b976bb6ffe7aa7cc
