### ISSUE TITLE
What does it mean in terminal npm

### ISSUE THREAD

**Issue by isaev8871** [z-classic/z-nomp#184]
mailformed message from (unautorized) [::ffff:202.61.84.196]; +&?Cookie: mstshash=hello

**Comment by aayanl** [comment]
safe to ignore, the pool is banning non-miners

**Comment by isaev8871** [comment]
elso question, sorry,, which ports needs open on incoming in firewall? 80 for webinterface, + my stratum ports, any also? for node?

**Comment by aayanl** [comment]
those two are fine, plus your node daemon's p2p port as well

**Comment by isaev8871** [comment]
THNX!

**Comment by isaev8871** [comment]
sorry,  
"p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
      

its need true? and 19333 open for incoming?

or 
"daemons": [
        {
            "host": "127.0.0.1",
            "port": 8231, - open for incoming?

**Comment by isaev8871** [comment]
and share rejected when block notification its normal?
