### ISSUE TITLE
Mined by: Someone using z-nomp!	

### ISSUE THREAD

**Issue by DrHyperKALICH** [z-classic/z-nomp#186]
Hello, how can I change "Mined by" in block explorer then using z-nomp?

**Comment by sennevb** [comment]
https://github.com/z-classic/node-stratum-pool/blob/master/lib/transactions.js line 60, change it by your own hex code

And pass this hex code to explorer's owner..

**Comment by fuzzewuzze** [comment]
@sennevb  Can you clarify?  If we're using Z-Nomp we arent using node-stratum-pool?  Trying to figure out exactly where this is and cant find it anywhere.

**Comment by sennevb** [comment]
The hex code will be sent in every blcok you find, block epxlorer will filter it out.

So basically yes

**Comment by interbiznw** [comment]
@Pacius You convert text to hex
