### ISSUE TITLE
work queue depth exceeded - What is!?

### ISSUE THREAD

**Issue by isaev8871** [z-classic/z-nomp#187]
request data: {"method":"getblocktemplate","params":[{"capabilities":["coinbasetxn","workid","coinbase/append"]}],
request data: {"method":"getblocksubsidy","params":[],"id":150...}}
response data: work queue depth exceeded

its red! and then all alright
what is this?

**Comment by hellcatz** [comment]
See if this info helps...
https://github.com/z-classic/z-nomp/issues/151
