### ISSUE TITLE
find block but it was rejectet by daemon, why?

### ISSUE THREAD

**Issue by isaev8871** [z-classic/z-nomp#188]
https://github.com/z-classic/z-nomp/issues/151 i do this, It because it???????????????????? hellcatz

**Comment by sennevb** [comment]
We need more info, block can be An orphan

**Comment by isaev8871** [comment]
where read more info? i do yesterday it:
"blockRefreshInterval": 0, use block notify scripts (note setup your coin daemon config!)
blocknotify=node /home/user/z-nomp/scripts/cli.js blocknotify 127.0.0.1:17117 zen %s
rpcworkqueue=64

and
Increase paymentInterval in pool_config
"paymentInterval": 600, 10 minute intervals

Increase walletInterval in pool_config
"walletInterval": 5, 5 minute intervals

Prior to these changes, this was not .....

**Comment by isaev8871** [comment]
its right i do?

**Comment by isaev8871** [comment]
i think because blockRefreshInterval 0, not it? and stats on site by payment block * of 100 very long refresh and stats block network refresh when refresh page.... ?

**Comment by sennevb** [comment]
whith info i mean what does terminal say when the block is rejected??

**Comment by hellcatz** [comment]
Note, the `error: confirmations: -1`  in the example block rejection below. The node rejected the orphaned block. Sometimes you have to check your coin daemon logs for more information on why the block may have been rejected. In the case of the block being orphaned, this is normal. Another pool/miner submitted the block and "beat you to it" causing yours to be orphaned.

```
...We thought a block was found but it was rejected by the daemon, share data: ...,"blockHash":"000000062607eb0d88e24b720628d47f2a721cb33509478c9ce9ab41738b1e21","error":{"confirmations":-1}}
```
