### ISSUE TITLE
No worker statistics on Edge or Internet Explorer

### ISSUE THREAD

**Issue by przemekh10** [z-classic/z-nomp#189]
Z-nomp worker's statistics are not working on Microsoft Edge and Internet Explorer.

Screnshot: https://image.ibb.co/exJxGk/z_nomp.png

**Comment by aayanl** [comment]
Edge I'll fix but IE will remain broken, sorry

**Comment by przemekh10** [comment]
Thanks!

**Comment by hellcatz** [comment]
Not 100% sure, but the PR referenced above may help.

**Comment by JimTriangle** [comment]
still not working on edge with those change
