### ISSUE TITLE
Fresh installs having same problem as regular nomp

### ISSUE THREAD

**Issue by bcmonster** [z-classic/z-nomp#190]
Error: Cannot find module 'stratum-pool'

I think they have put in a pull request for the versions.  I have worked on getting around this for hours now.   Any Idea?   I got past this once but landed on bignum error.  Worked my way back around to this one again.  

Any Ideas?

**Comment by bcmonster** [comment]
Here is the link to the other issue.   

https://github.com/zone117x/node-open-mining-portal/issues/489

If you guys have any idea what versions I need to try and download to get past this I would appreciate it.

**Comment by sennevb** [comment]
did you do npm update and npm install??

**Comment by bcmonster** [comment]
Absolutely.   I'm running 14.4 in wonder if going to a new version of Ubuntu would fix it.   I run nomp on my Bitcoin pool for 2 years now no issue.

**Comment by sennevb** [comment]
weird :-/

**Comment by bcmonster** [comment]
It might have been my stupidity.  I was trying to run it like i do my bitcoin pool with node init.js instead of npm.....  I also updated to 16.04

**Comment by sennevb** [comment]
can be.. lemme know if it helps

**Comment by aayanl** [comment]
Nomp requires node 0.10 while znomp requires >v4

**Comment by madbuda** [comment]
To start without using npm use this

`LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js`
