### ISSUE TITLE
Zero

### ISSUE THREAD

**Issue by DrHyperKALICH** [z-classic/z-nomp#191]
Hello!

Trying to add Zero
from
https://github.com/zerocurrency/zero

But then mining I get 

in pool logs:

We thought a block was found but it was rejected by the daemon, share data: {"job":"cd41","ip":"::ffff:123.21.82.215","port":13333,"worker":"t1QttC5Vqo4CtiEiLkETpY13wuh3SDPJsQk.rig0","height":138356,"difficulty":3.63215153,"shareDiff":"333.23553124","blockDiff":78.487466763,"blockDiffActual":78.487466763,"blockHash":"00000625535c11d3ae5c5a172d5af8f8a457dfe0aac4bf9123b523c60b1dfd6d","error":{"unknown":"check coin daemon logs"}}

in daemon logs:

CreateNewBlock(): total size 1000
 keypool return 2
 ERROR: CheckEquihashSolution(): invalid solution
 ERROR: CheckBlockHeader(): Equihash solution invalid
 ERROR: ProcessNewBlock: CheckBlock FAILED

zero.conf

zero.json
{
    "name": "zero",
    "symbol": "zer",
    "algorithm": "equihash",
    "requireShielding": false,
    "txfee": 0.0001
}

May be someone can help me?

**Comment by aayanl** [comment]
Zero needs some changes with the stratum to get working and I've never been able to get in contact with the dev
