### ISSUE TITLE
Immature Balance Tracking

### ISSUE THREAD

**Issue by hellcatz** [z-classic/z-nomp#194]
Bounty Request for adding Immature Balance tracking to z-nomp, please support this bounty.

Add required changes to api.
Add required changes to stats.
Add immature tracking to redis.
Add immature tracking to payment processor.
Misc improvements to related areas.

Bounty Requested of (200 HUSH)
Bounty Address HUSH: t1YVGof2ccsQAeRFETo52FYMh295b4AWt2M

https://explorer.myhush.org/address/t1YVGof2ccsQAeRFETo52FYMh295b4AWt2M

**Comment by madbuda** [comment]
Hush project will pay the full bounty, I'll update once payment is complete

**Comment by danycoman** [comment]
hellcatz is the best!

**Comment by radix42** [comment]
this sounds awesome, as soon as its ready to go and its pushed and tested, I'll send to that address

**Comment by radix42** [comment]
Bounty paid, thank you for helping improve the entire equihash ecosystem!
http://explorer.myhush.org/tx/12b8e4da089b27875428b8ebac8943cddfe3ce3adf73d6f819e8e893a5856613
