### ISSUE TITLE
Pool not generating full reward

### ISSUE THREAD

**Issue by Tomas-M** [z-classic/z-nomp#198]
Hello,
I am trying to setup z-nomp for VoteCoin mining. It is a zcash fork. Block reward should be 125 VOT.

I copied settings from zclassic.json.
When new block is found, it only adds 100 VOT instead of 125.
As you can see here:
http://pool.votecoin.site/stats
Example block:
http://explorer.votecoin.site/block/00000c6b87f7e982e40327b84971e19a24d793ac7ca4bf76a50fd8fb9ebea455

Mining with votecoind daemon on Linux properly gives 125 VOT.
But mining through the pool gives 100 VOT.
Are you aware of any configuration which is required to fix this?
I am expecting to receive 125 VOT reward, not 100.
Thank you

**Comment by Tomas-M** [comment]
This is my votecoin.json file in coins folder:

    {
        "name": "votecoin",
        "symbol": "VOT",
        "algorithm": "equihash",
        "requireShielding": true,
        "peerMagic": "24e92764",
        "percentFoundersReward": 0,
        "payFoundersReward": false,
        "txfee": 0.0000
    }

And in pool_config, I have

    "rewardRecipients": {
    },

    "paymentProcessing": {
        "minConf": 10,
        "enabled": true,
        "paymentMode": "pplnt",
        "_comment_paymentMode":"prop, pplnt",
        "paymentInterval": 20,
        "minimumPayment": 1,
        "maxBlocksPerPayment": 3,
        ...
        ...

**Comment by Tomas-M** [comment]
Aah, I think I found the problem.
I forgot (in the sources of forked zcash) to return proper block reward and founders reward on the RPC API, so it returned wrong reward. I'm now recompiling the sources to see if this is fixed after returning correct reward. Will close this issue if this is correct.

**Comment by Tomas-M** [comment]
Yeah that was it. Sorry for blaming your ingenious software :) Closing this issue.

**Comment by lutsifer** [comment]
Hey @Tomas-M Sorry for bothering you, but I saw your pool working (I wish i could say same for mine)

I build zclassic pool with z-nomp. It works good, no warnings at all. 
Just no reward at all either :) :)
The pool calculates for me 2.5 days luck (with 4.2 KSols/s) and I am mining already pretty much 2 days and I don't have even single orphaned block discovered :(

All I read inside debug log repeating over and over again is:

2017-10-04 19:26:26 UpdateTip: new best=00000001fb955f21b5ce2525bf1e870565416b015984505b7e900e62add34dec  height=189099  log2_work=45.871881  tx=463886  date=2017-10-04 19:25:11 progress=0.999992  cache=0.0MiB(35tx)
2017-10-04 19:26:26 keypool reserve 4
2017-10-04 19:26:26 CreateNewBlock(): total size 1000
2017-10-04 19:26:26 keypool return 4
2017-10-04 19:26:45 keypool reserve 4
2017-10-04 19:26:45 CreateNewBlock(): total size 2943
2017-10-04 19:26:46 keypool return 4
2017-10-04 19:27:06 keypool reserve 4
2017-10-04 19:27:06 CreateNewBlock(): total size 4886
2017-10-04 19:27:07 keypool return 4
2017-10-04 19:27:12 keypool reserve 4
2017-10-04 19:27:12 CreateNewBlock(): total size 6829
2017-10-04 19:27:12 keypool return 4

my conf looks like this:

addnode=dnsseed.zclassic.org:8133
addnode=dnsseed.rotorproject.org:8133
addnode=104.207.149.241:8133
addnode=45.76.4.70:8133
****other peers****
rpcuser=long username
rpcpassword=long long password
daemon=1
rpcport=8232
blocknotify=node /root/z-nomp/scripts/cli.js blocknotify zclassic %s

npm block is boring too:

 2017-10-04 19:24:37 [Pool]	[zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
0|npm      | 2017-10-04 19:25:32 [Pool]	[zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
0|npm      | 2017-10-04 19:26:02 [Payments]	[zclassic] Finished interval - time spent: 6ms total, 2ms redis, 3ms daemon RPC
0|npm      | 2017-10-04 19:26:26 [Pool]	[zclassic] (Thread 1) Block notification via RPC polling
0|npm      | 2017-10-04 19:26:27 [Pool]	[zclassic] (Thread 1) Block notification via blocknotify script
0|npm      | 2017-10-04 19:27:21 [Pool]	[zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
0|npm      | 2017-10-04 19:28:16 [Pool]	[zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
0|npm      | 2017-10-04 19:29:02 [Payments]	[zclassic] Finished interval - time spent: 19ms total, 4ms redis, 12ms daemon RPC
0|npm      | 2017-10-04 19:29:11 [Pool]	[zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
0|npm      | 2017-10-04 19:30:06 [Pool]	[zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
0|npm      | 2017-10-04 19:31:01 [Pool]	[zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
0|npm      | 2017-10-04 19:31:56 [Pool]	[zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
0|npm      | 2017-10-04 19:32:02 [Payments]	[zclassic] Finished interval - time spent: 7ms total, 3ms redis, 4ms daemon RPC
0|npm      | 2017-10-04 19:32:51 [Pool]	[zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
0|npm      | 2017-10-04 19:33:46 [Pool]	[zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work

Everyone tells me it is completely normal but... 
I don't know how to really test it does it work :(
I am so close to order nicehash hard artillery to test it out at the end..

Any help would be highly appreciated !

**Comment by sennevb** [comment]
If you have doubt and want to test, use testnet.
But your log doesnt show anything weird, hash is just low VS net hash. It just takes time to find a block

**Comment by lutsifer** [comment]
@sennevb 
I am not sure what peers to use for testnet zclassic. It is a bit hard with the documentation there. Do you know them by chance?

**Comment by lutsifer** [comment]
@sennevb I did try with the production ones but they simply refused to connect (as expected)

**Comment by lutsifer** [comment]
@sennevb It works! Thank you!
