### ISSUE TITLE
Many orphaned blocks 

### ISSUE THREAD

**Issue by web-premier** [z-classic/z-nomp#204]
Hello!

I make pool with komodo.
Conf:
`{
    "enabled":true,
    "coin": "komodo.json",

    "address": "RCXQ9B4Qa7BXG4vxynRz23GcYxFiZ4sXSN",
    "_comment_address": "pools komodo address; ex, RSXGTHQSqwcMw1vowKfEE7sQ8fAmv1tmso",

    "zAddress": "zccQmhziYWsbGAXaGwByp55anXP5PRpDYozBAQwgGSkMCpyrvYPcUWJaHKQzWubU7dECHzvvTYeXoAAr2TjwzdHob3i3gZ9",
    "_comment_zAddress": "shielding not required in komodo, not used",

    "tAddress": "RCXQ9B4Qa7BXG4vxynRz23GcYxFiZ4sXSN",
    "_comment_tAddress": "set to same as pools komodo address; ex, RSXGTHQSqwcMw1vowKfEE7sQ8fAmv1tms",

    "walletInterval": 1,
    "_comment_walletInterval": "Used to cache komodo coin stats, shielding not performed.",

    "rewardRecipients": {
        "RP1YUSanCSDJZ4caLXJx2gmNmeu1mmdMA7": 0.5
    },

    "tlsOptions": {
        "enabled": false,
        "serverKey":"",
        "serverCert":"",
        "ca":""
    },

    "paymentProcessing": {
	   "minConf": 10,
        "enabled": true,
        "paymentMode": "prop",
        "_comment_paymentMode":"prop, pplnt",
        "paymentInterval": 57,
        "_comment_paymentInterval": "Interval in seconds to check and perform payments.",
        "minimumPayment": 0.1,
        "maxBlocksPerPayment": 3,
        "daemon": {
            "host": "127.0.0.1",
            "port": 8235,
            "user": "user",
            "password": "ppp"
        }
    },

    "ports": {
        "3857": {
            "tls":false,
            "diff": 1,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 8235,
            "user": "user",
            "password": "ppp"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "kmd",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}
`
4 hour with 30KSol/s founded 90 orphaned blocks and no one confirmed.
In log:
2017-09-29 18:33:47 [Pool]      [komodo] (Thread 8) Daemon instance 0 rejected a supposedly valid block
2017-09-29 18:33:56 [Pool]      [komodo] (Thread 2) We thought a block was found but it was rejected by the daemon, share data: {"job":"d3f7","ip":"::ffff:37.58.65.213","port":3857,"worker":"RP1YUSanCSDJZ4caLXJx2gmNmeu1mmdMA7","height":146228,"difficulty":16,"shareDiff":"31.32544605","blockDiff":7.671646596,"blockDiffActual":7.671646596,"blockHash":"00004160cf0b4e7bf7a3347a3fc06dc1395662478eab6d6163bb1c50268a3e4c","error":{"confirmations":-1}}

Can you help me? It all right?

Sorry for my bad english...

**Comment by aayanl** [comment]
Your `address` and `tAddress` are the same, you need to change it

**Comment by lutsifer** [comment]
This hardly will explain orphaned blocks:)

**Comment by madbuda** [comment]
@lutsifer I would suggest talking to someone on the Komodo team regarding orphan rates, this isn't something controlled by z-nomp

**Comment by lutsifer** [comment]
True, however it turns out there is no orphaned blocks on my side:)
@madbuda cheers, after 2 3 days you will have brand new modern 0% fee pool:
https://zcl.ludizain.com
I have to finish up some statistics, but this aside - it works gourdes:)

**Comment by lutsifer** [comment]
I guess it will need a proper name though ...

**Comment by bcmonster** [comment]
There is no z address with Komodo.  You need to remove that whole section.

**Comment by madbuda** [comment]
@bcmonster no, it would depend on the coins/komodo.json if he has shielding enabled or not, just because an config item exists doesn't mean it is being used.
