### ISSUE TITLE
I can not connect my miner. Stratum?

### ISSUE THREAD

**Issue by neurans** [z-classic/z-nomp#205]
I can not connect my miner. Stratum?
Do I need to install stratum? I see no steps in the guide.

I can MIne without the stratum:
this works :::
miner --server equihashing.com --user t1TSHHcf1D9eNdWJd2MrSdJLwQvzzCd3r6o.cmilian --pass z --port 3333 --log

This does not work: 
miner --server stratum+tcp://equihashing.com --user t1TSHHcf1D9eNdWJd2MrSdJLwQvzzCd3r6o.cmilian --pass z --port 3333 --log

**Comment by aayanl** [comment]
so stick to what works

**Comment by neurans** [comment]
Nicehash needs stratum, will it work without the prefix?

**Comment by aayanl** [comment]
yes
