### ISSUE TITLE
z-nomp don't sending funds from taddr to zaddr

### ISSUE THREAD

**Issue by flexmankz** [z-classic/z-nomp#219]
Don't know where I should fix that issue:
[votecoin] sendmany "" {"t1XmGD............................................................":124.45000362}
[votecoin] Error sending payments {"code":-6,"message":"Insufficient funds, coinbase funds can only be spent after they have been sent to a zaddr"}

Any guesses?

**Comment by flexmankz** [comment]
resolve it by my self...

**Comment by litecoinz-project** [comment]
Dear flexmankz,
could you explain how did you fix it?
May be I have the same issue.
Thanks
