### ISSUE TITLE
Cannot get /[page]

### ISSUE THREAD

**Issue by Coronon** [z-classic/z-nomp#245]
Hello, everything works fine, but if i add a new page under website\pages\ and i want to open that page i just get the error "Cannot GET /[page]". Please help.

**Comment by ptantiku** [comment]
I think you need to add the page file name and alias in libs/website.js
https://github.com/z-classic/z-nomp/blob/e1eba6d88ff3f0ed8692714ba8e7222ef01b3071/libs/website.js#L35-L47
