### ISSUE TITLE
Not showing network stats

### ISSUE THREAD

**Issue by aazm** [z-classic/z-nomp#269]
Hello, guys!
I'm having very weird issue. 
For some coins I can't see network statistics on frontend.

Sometimes flushing all from Redis helps me to fix it, sometimes not.

<img width="1150" alt="2018-01-14_2001" src="https://user-images.githubusercontent.com/5412765/34918585-bbe6e96c-f965-11e7-883a-9b28d6689ed6.png">

Do u have any thoughts about that?
Thanks!

**Comment by aazm** [comment]
sorry, found solution in other issue!

**Comment by botio** [comment]
how did u fix it ? i have the same problem now .

**Comment by aazm** [comment]
super easy, just enable paymentProcessing in coin config
