### ISSUE TITLE
No Finds blocks zcash

### ISSUE THREAD

**Issue by bigenergy** [z-classic/z-nomp#281]
Mining 10 KSol/s, can't find any block for the past 48 hours! Is this normal?

**Comment by sennevb** [comment]
I hope you are joking...

**Comment by bigenergy** [comment]
10 KSol/s* sorry

**Comment by bigenergy** [comment]
Please hepl me :(

**Comment by bigenergy** [comment]
@sennevb

**Comment by Kosta85** [comment]
You can search zcash block with 10 ksol during years, the network and difficult ate in the sky. Try other coins... Look at luck in stats

**Comment by Xandrah** [comment]
Uhhhh.. you wont find a zcash block in years, you need about 900 KH/s to even start

**Comment by bigenergy** [comment]
What currency would you recommend?

**Comment by Kosta85** [comment]
Something lite, like votecoin or snowgem

**Comment by bigenergy** [comment]
But what about zen or zcl?

**Comment by Kosta85** [comment]
Not a good idea to mine zen or zcl in solo, you can search block on Zen during month(s) with 10 ksol, network is around 40 msol... on zcl it's more harder

**Comment by dangerm0us** [comment]
My pool is finding blocks with ~300KSol/s
