### ISSUE TITLE
Error, founders reward missing for block template [ZEN]

### ISSUE THREAD

**Issue by bigenergy** [z-classic/z-nomp#284]
Error, founders reward missing for block template!
for zencash

**Comment by bigenergy** [comment]
> [zen] (Thread 4) getblocktemplate call failed for daemon instance 0 with error {"code":-1,"message":"CreateNewBlock(): TestBlockValidity failed"}

**Comment by k4k** [comment]
Also receiving message `Error, founders reward missing for block template!` when configured with ZenCash. I've added the lines to `zen.json` as defined in #170 but the log spam persists. I can't see how it would be related but I don't recall seeing this message prior to re-configuring zend to run under an unprivileged user.

@bigenergy how did you produce the `getblocktemplate` error. I would like to attempt to see if I can observe it on my server.
