### ISSUE TITLE
how to add comment to the transaction in z-nomp

### ISSUE THREAD

**Issue by zzgang** [z-classic/z-nomp#305]
i want to add a comment to the transaction,etc domain name.

**Comment by interbiznw** [comment]
it is done in the node module "node-stratum-pool" Not in z-nomp

**Comment by zzgang** [comment]
i just want to add my pool web site domain name to the transaction. can you tell me the details?

**Comment by zzgang** [comment]
in bitcoinjs-lib-zcash?

**Comment by MCrypto** [comment]
i think its in "transactions.js" under node_modules/stratum-pool/lib on line 60:

>    tx.addInput(new Buffer('0000000000000000000000000000000000000000000000000000000000000000', 'hex'),
        4294967295,
        4294967295,
        new Buffer.concat([serializedBlockHeight,
            Buffer('5a2d4e4f4d50212068747470733a2f2f6769746875622e636f6d2f6a6f7368756179616275742f7a2d6e6f6d70', 'hex')]) //Z-NOMP! https://github.com/joshuayabut/z-nomp
    );

what you want is to change the hex part to what you want it to say:

> Buffer('5a2d4e4f4d50212068747470733a2f2f6769746875622e636f6d2f6a6f7368756179616275742f7a2d6e6f6d70', 'hex')])

i tried this before ... but it never worked for me :)))

**Comment by zzgang** [comment]
yes, it does not work by default!

**Comment by zzgang** [comment]
anybody show me the code details?
