### ISSUE TITLE
No new blocks find at zclassic

### ISSUE THREAD

**Issue by dimdanm** [z-classic/z-nomp#307]
Hello. I started z-nomp at 3 days ago. All is looking fine: graphs, shares, users, auth, etc. No errors found. But i can not find at least 1 block for 3 days. I have calculated, that with my speed of 120 ksol/sec i must found first share after 7 hours of work.  I still wait, but 0 blocks found. What i can do to check all functionality of this software z-nomp?

**Comment by zzgang** [comment]
whether if find the shares?

**Comment by dimdanm** [comment]
Of couse no. But i want to find at least 1 block for experiment, that is why i add the additional mining power from nisehash, but never find a block.

**Comment by nimbosa** [comment]
it all depends on "luck" and you have to compete with hashpower of other mining pools and solo miners to find a block first..
