### ISSUE TITLE
Block set at pool like Orphaned, but I receive coins to pool wallet.

### ISSUE THREAD

**Issue by AlexSpain** [z-classic/z-nomp#310]
I have problem with block what pool place like orphaned and not send reward to miners.
But I have coins for this block at wallet and it not orphaned block.
How I can send reward to miners?

**Comment by crutched** [comment]
Pool removes all data about orphaned round (and add shares to the current round).
Your payment instance was connected to out of sync daemon. If the daemon can't find tx of generated block, pool think this block was orphaned.

**Comment by AlexSpain** [comment]
Can I run reward script again and setup reward
Do I need to set txindex=1 at coin daemon to prevent this? 
How I can prevent this? 
Daemon have 12 nodes connected and I think is sync fine.

Can we speak at Discord or Skype? I can speak English, Spanish, Russian.
