### ISSUE TITLE
Not getting payments using ZCash and Z-NOMP

### ISSUE THREAD

**Issue by zaggwarrior** [z-classic/z-nomp#311]
I am sorry if this is posted in the wrong group:

Guys, this is most likely a rookie mistake, but I have everything up and running.  I do not see any errors appearing.  Looking at the logs, everything is humming along nicely.  I am getting blocks, working blocks, collecting shares and everything else that you would expect.  The minor is connecting and finding accepted shares.  The big catch - I have not received anything in my wallet.  

./zcash-cli listtransactions is [ ] (Blank)

./zcash-cli z_gettotalbalance shows zero's for everything

./zcash-cli z_listaddresses shows addresses

./zcash-cli listaccounts shows
{
 "": 0.00000000
}

Any help would be greatly appreciated.  I have googled quite a bit, but I keep finding dead-ends.

Thanks

**Comment by AlexSpain** [comment]
what is your coin? show please coin config.

**Comment by zaggwarrior** [comment]
I am trying to mine ZCash.  Here are my configs:

Config.json
{
    "logLevel": "debug",
    "logColors": true,

    "cliPort": 17117,

    "clustering": {
        "enabled": true,
        "forks": "auto"
    },

    "defaultPoolConfigs": {
        "blockRefreshInterval": 0,
        "jobRebroadcastTimeout": 55,
        "connectionTimeout": 600,
        "emitInvalidBlockHashes": false,
        "validateWorkerUsername": true,
        "tcpProxyProtocol": false,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 500,
            "purgeInterval": 300
        },
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "password": ""
        }
    },

    "website": {
        "enabled": true,
        "host": "0.0.0.0",
        "port": 8080,
        "stratumHost": "cryppit.com",
        "stats": {
            "updateInterval": 30,
            "historicalRetention": 14400,
            "hashrateWindow": 300
        },
        "adminCenter": {
            "enabled": false,
            "password": "password"
        },
        "tlsOptions" : {
            "enabled": false,
            "cert": "",
            "key": ""
        }
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "switching": {
        "switch1": {
            "enabled": false,
            "algorithm": "sha256",
            "ports": {
                "3333": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch2": {
            "enabled": false,
            "algorithm": "scrypt",
            "ports": {
                "4444": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch3": {
            "enabled": false,
            "algorithm": "x11",
            "ports": {
                "5555": {
                    "diff": 0.001,
                    "varDiff": {
                        "minDiff": 0.001,
                        "maxDiff": 1,
                        "targetTime": 15,
                        "retargetTime": 60,
                        "variancePercent": 30
                    }
                }
            }
        }
    },

    "profitSwitch": {
        "enabled": false,
        "updateInterval": 600,
        "depth": 0.90,
        "usePoloniex": true,
        "useCryptsy": true,
        "useMintpal": true,
        "useBittrex": true
    }
}


------------------------------------------------------------------------------------------
zcash.json
{
    "enabled": true,
    "coin": "zcash.json",

    "address": "******",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "******",

    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "******",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "walletInterval": 2.5,

    "rewardRecipients": {
           "******": 0.2
    },

    "paymentProcessing": {
	"minConf": 10,
        "enabled": true,
        "paymentMode": "pplnt",
        "_comment_paymentMode":"prop, pplnt",
        "paymentInterval": 120,
        "minimumPayment": 0.01,
        "maxBlocksPerPayment": 3,
        "daemon": {
            "host": "127.0.0.1",
            "port": 8232,
            "user": "******",
            "password": "******"
        }
    },

    "tlsOptions": {
        "enabled": false,
        "serverKey":"",
        "serverCert":"",
        "ca":""
    },

    "ports": {
        "3333": {
            "diff": 0.05,
            "tls": false,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 8232,
            "user": "******",
            "password": "******"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "zec",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}

------------------------------------------------------------------------------------------
zcash.json

addnode=mainnet.z.cash
genproclimit=-1
equihashsolver=tromp
rpcuser=******
rpcpassword=******
rpcport=8232
rpcworkqueue=64
daemon=1
server=1
gen=1
paytxfee=0.004
blocknotify=node /home/miningpool/z-nomp/scripts/cli.js blocknotify zcoin %s

**Comment by theicosuperman** [comment]
I can suggest you send an extra coint  to the "address": "******", it helped me

**Comment by zaggwarrior** [comment]
Do you have a good suggestion on an amount?

**Comment by theicosuperman** [comment]
1 HUSH worked fine.

**Comment by zaggwarrior** [comment]
Thank you.
