### ISSUE TITLE
Someone using z-nomp!

### ISSUE THREAD

**Issue by christianreiss** [z-classic/z-nomp#321]
Hey folks,

I am doing solo-mining utilizing Z-NOMP. On a block explorer like 

- https://explorer.myhush.org/block/00000008a17a29249234c5514e55db92e97252e3c6d4b7e96bd0f9ba5c68cee7

there is the information "Mined By" with "Someone using z-nomp!" as value. Others have the names of their pools there. Where does that information come from? I would love to what my (Nick)name there!

Cheers!
-Chris.

**Comment by TheComputerGenie** [comment]
It comes from here:
https://github.com/z-classic/node-stratum-pool/blob/master/lib/transactions.js#L60
and a tag set by the owner of the explorer.

FYI:
> 5a2d4e4f4d50212068747470733a2f2f6769746875622e636f6d2f6a6f7368756179616275742f7a2d6e6f6d70

is the Hex for the ASCII:

> Z-NOMP! https://github.com/joshuayabut/z-nomp
