### ISSUE TITLE
error, please help

### ISSUE THREAD

**Issue by jrischma** [z-classic/z-nomp#322]
root@etc:~/BTCP/z-nomp# sudo npm start

> z-nomp@0.0.4 start /root/BTCP/z-nomp
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

2018-04-12 18:42:58 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2018-04-12 18:42:58 [Master]    [config.json] Pool has same configured coin file coins/btcp.json as btcp.json pool
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! z-nomp@0.0.4 start: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the z-nomp@0.0.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

thanks

**Comment by jrischma** [comment]
solved

**Comment by NINGPOOL1** [comment]
how to npm update?
can you tell me cmd?
I update npm is false.

**Comment by igorvoltaic** [comment]
@cpuccc
```shell 
$ git clone https://github.com/z-classic/z-nomp
$ git checkout master && git pull
$ cd z-nomp/
$ npm update
```

or just read README.md
