### ISSUE TITLE
 equihashverify from joshuayabut to zencashofficial ,npm update wrong 

### ISSUE THREAD

**Issue by xianxiongwang** [z-classic/z-nomp#328]
equihashverify from joshuayabut to zencashofficial ,npm update wrong 

edz@edz-MS-7996:/work/opensourcepool/github.com/z-classic/z-nomp$ npm update

> equihashverify@0.0.2 install /work/opensourcepool/github.com/z-classic/z-nomp/node_modules/equihashverify
> env V=1 node-gyp rebuild

make: Entering directory '/work/opensourcepool/github.com/z-classic/z-nomp/node_modules/equihashverify/build'
  g++ '-DNODE_GYP_MODULE_NAME=equihashverify' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DHAVE_DECL_STRNLEN=1' '-DHAVE_BYTESWAP_H=1' '-DBUILDING_NODE_EXTENSION' -I/home/edz/.node-gyp/9.11.1/include/node -I/home/edz/.node-gyp/9.11.1/src -I/home/edz/.node-gyp/9.11.1/deps/uv/include -I/home/edz/.node-gyp/9.11.1/deps/v8/include -I../../nan -I../. -I/usr/include -I/usr/include/boost  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++11 -Wl,--whole-archive -fPIC -fexceptions -MMD -MF ./Release/.deps/Release/obj.target/equihashverify/support/cleanse.o.d.raw   -c -o Release/obj.target/equihashverify/support/cleanse.o ../support/cleanse.cpp
  g++ '-DNODE_GYP_MODULE_NAME=equihashverify' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DHAVE_DECL_STRNLEN=1' '-DHAVE_BYTESWAP_H=1' '-DBUILDING_NODE_EXTENSION' -I/home/edz/.node-gyp/9.11.1/include/node -I/home/edz/.node-gyp/9.11.1/src -I/home/edz/.node-gyp/9.11.1/deps/uv/include -I/home/edz/.node-gyp/9.11.1/deps/v8/include -I../../nan -I../. -I/usr/include -I/usr/include/boost  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++11 -Wl,--whole-archive -fPIC -fexceptions -MMD -MF ./Release/.deps/Release/obj.target/equihashverify/uint256.o.d.raw   -c -o Release/obj.target/equihashverify/uint256.o ../uint256.cpp
  g++ '-DNODE_GYP_MODULE_NAME=equihashverify' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DHAVE_DECL_STRNLEN=1' '-DHAVE_BYTESWAP_H=1' '-DBUILDING_NODE_EXTENSION' -I/home/edz/.node-gyp/9.11.1/include/node -I/home/edz/.node-gyp/9.11.1/src -I/home/edz/.node-gyp/9.11.1/deps/uv/include -I/home/edz/.node-gyp/9.11.1/deps/v8/include -I../../nan -I../. -I/usr/include -I/usr/include/boost  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++11 -Wl,--whole-archive -fPIC -fexceptions -MMD -MF ./Release/.deps/Release/obj.target/equihashverify/arith_uint256.o.d.raw   -c -o Release/obj.target/equihashverify/arith_uint256.o ../arith_uint256.cpp
  g++ '-DNODE_GYP_MODULE_NAME=equihashverify' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DHAVE_DECL_STRNLEN=1' '-DHAVE_BYTESWAP_H=1' '-DBUILDING_NODE_EXTENSION' -I/home/edz/.node-gyp/9.11.1/include/node -I/home/edz/.node-gyp/9.11.1/src -I/home/edz/.node-gyp/9.11.1/deps/uv/include -I/home/edz/.node-gyp/9.11.1/deps/v8/include -I../../nan -I../. -I/usr/include -I/usr/include/boost  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -std=c++11 -Wl,--whole-archive -fPIC -fexceptions -MMD -MF ./Release/.deps/Release/obj.target/equihashverify/random.o.d.raw   -c -o Release/obj.target/equihashverify/random.o ../random.cpp
In file included from ../random.cpp:9:0:
**../serialize.h:23:27: fatal error: boost/array.hpp:** 没有那个文件或目录
compilation terminated.
equihashverify.target.mk:129: recipe for target 'Release/obj.target/equihashverify/random.o' failed
make: *** [Release/obj.target/equihashverify/random.o] Error 1
make: Leaving directory '/work/opensourcepool/github.com/z-classic/z-nomp/node_modules/equihashverify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /work/opensourcepool/github.com/z-classic/z-nomp/node_modules/equihashverify
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! equihashverify@0.0.2 install: `env V=1 node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the equihashverify@0.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/edz/.npm/_logs/2018-04-21T12_40_48_774Z-debug.log

**Comment by Punkoivan** [comment]
Hello @xianxiongwang , could you please show a way to fix this? got something like this.

thanks in advance.

**Comment by sennevb** [comment]
Make sure you installed all dependencies needed for the neW equihashverify

**Comment by northdakota** [comment]
@xianxiongwang you need to install equihashverify package 
from this instruction https://github.com/ZencashOfficial/equihashverify
```
sudo apt-get install build-essential libsodium-dev libboost-system-dev
sudo npm install -g mocha
npm install
```
