### ISSUE TITLE
Graph rendering loads CPU up to 100%

### ISSUE THREAD

**Issue by theicosuperman** [z-classic/z-nomp#331]
Firefox is hanging up, opera is working but slowly.

![default](https://user-images.githubusercontent.com/37374894/39352515-a3a314d6-4a0d-11e8-9d7f-10e4a1658cfa.png)

**Comment by sennevb** [comment]
Javascript is handled on cliënt side, so this can be normal..

**Comment by theicosuperman** [comment]
I did this in config.json
 "stats": {
            "updateInterval": 0.1,
            "historicalRetention": 172800,
            "hashrateWindow": 30
        },

Unfortunately I don't know how to make graph update more often. Is this possible?

**Comment by TheComputerGenie** [comment]
You set it to "gather stats to broadcast to page viewers **and** store in redis for historical stats" at a rate of **10 times per second**, you want it to update more than that, and you think it shouldn't use CPU?

**Comment by TheComputerGenie** [comment]
You set it to hold 2 days worth of info; used 30 seconds as your time of "_seconds worth of shares should be gathered to generate hashrate_"; and "_gather stats to broadcast to page viewers **and** store in redis for historical stats_" at a rate of **10 times per second**, and you're confused as to why it pegs the CPU?

**and now you want it to update more often than that**?

**Comment by theicosuperman** [comment]
Wow, I completely missed out updateInterval time stretch. for now I understand what was really wrong. Thank you for explanation. After I turend "updateInterval":  to 1, I don't see this cpu load no more. Btw redis ops/s was more than 200 in this setting.
