### ISSUE TITLE
 Command failed: /usr/bin/git clone

### ISSUE THREAD

**Issue by dacelee** [z-classic/z-nomp#347]
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/z-classic/node-stratum-pool.git /home/pool/.npm/_cacache/tmp/git-clone-8dd20a0d
npm ERR! /home/pool/.npm/_cacache/tmp/git-clone-8dd20a0d/.git: Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:

**Comment by dacelee** [comment]
m ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by igorvoltaic** [comment]
which version of Nodejs do you have?

**Comment by TheComputerGenie** [comment]
> Permission denied

https://www.pluralsight.com/blog/it-ops/linux-file-permissions

**Comment by igorvoltaic** [comment]
Nodejs version?

**Comment by dacelee** [comment]
sudo n 8.9.4  Solve my problem
