### ISSUE TITLE
 [Payments] [zelcash] Insufficient funds (149.9998) to process payments (150); possibly waiting for txs.

### ISSUE THREAD

**Issue by angona2** [z-classic/z-nomp#357]
Just wanted to test out getting a block of Zelcash and after finding the block it has been stuck on pending for quite some time. Any ideas?

1. z_gettotalbalance
`  "transparent": "149.9998",
  "private": "0.00",
  "total": "149.9998"`

2. getwalletinfo
`  "walletversion": 60000,
  "balance": 149.99980000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 4,
  "keypoololdest": 1529606620,
  "keypoolsize": 101,
  "paytxfee": 0.00000000
`

3. 243/100 confirmations currently

4. coins/zelcash.json
`    "name": "zelcash",
    "symbol": "zel",
    "algorithm": "equihash",
    "requireShielding": true,
    "txfee": 0.0001
`

5. in pool_configs/zelcash.json...
`minConf = 10
minimumPayment = 1
maxBlocksPerPayment = 100`

**Comment by c2h2** [comment]
post full pool_configs/zelcash.json(the pool config)

**Comment by angona2** [comment]
@c2h2 


Config.json:

{
    "logLevel": "debug",
    "logColors": true,

    "cliPort": 17117,

    "clustering": {
        "enabled": true,
        "forks": "auto"
    },

    "defaultPoolConfigs": {
        "blockRefreshInterval": 0,
        "jobRebroadcastTimeout": 100,
        "connectionTimeout": 250,
        "emitInvalidBlockHashes": true,
        "validateWorkerUsername": true,
        "tcpProxyProtocol": false,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 500,
            "purgeInterval": 300
        },
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "password": ""
        }
    },

    "website": {
        "enabled": true,
        "host": "xx.xx.xx.xx",
        "port": 8084,
        "stratumHost": "xx.xx.xx.xx",
        "stats": {
            "updateInterval": 30,
            "historicalRetention": 14400,
            "hashrateWindow": 300
        },
        "adminCenter": {
            "enabled": true,
            "password": "password"
        },
        "tlsOptions" : {
            "enabled": false,
            "cert": "",
            "key": ""
        }
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    },

    "switching": {
        "switch1": {
            "enabled": false,
            "algorithm": "sha256",
            "ports": {
                "3333": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch2": {
            "enabled": false,
            "algorithm": "scrypt",
            "ports": {
                "4444": {
                    "diff": 10,
                    "varDiff": {
                        "minDiff": 16,
                        "maxDiff": 512,
                        "targetTime": 15,
                        "retargetTime": 90,
                        "variancePercent": 30
                    }
                }
            }
        },
        "switch3": {
            "enabled": false,
            "algorithm": "x11",
            "ports": {
                "5555": {
                    "diff": 0.001,
                    "varDiff": {
                        "minDiff": 0.001,
                        "maxDiff": 1,
                        "targetTime": 15,
                        "retargetTime": 60,
                        "variancePercent": 30
                    }
                }
            }
        }
    },

    "profitSwitch": {
        "enabled": false,
        "updateInterval": 600,
        "depth": 0.90,
        "usePoloniex": true,
        "useCryptsy": true,
        "useMintpal": true,
        "useBittrex": true
    }
}



zelcash.json

{
    "enabled": true,
    "coin": "zelcash.json",

    "address": "t1.........",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "zc.............",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "t1.....",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "walletInterval": 5,

    "rewardRecipients": {

    },

    "paymentProcessing": {
	"minConf": 10,
        "enabled": true,
        "paymentMode": "prop",
        "_comment_paymentMode":"prop, pplnt",
        "paymentInterval": 600,
        "minimumPayment": 1,
        "maxBlocksPerPayment": 100,
        "daemon": {
            "host": "127.0.0.1",
            "port": 16124,
            "user": "secret password",
            "password": "secret username"
        }
    },

    "tlsOptions": {
        "enabled": false,
        "serverKey":"",
        "serverCert":"",
        "ca":""
    },

    "ports": {
        "3040": {
            "diff": 0.05,
            "tls": false,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 16124,
            "user": "secret username",
            "password": "secret password"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "zec",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}

**Comment by c2h2** [comment]
"address": "t1.........",  == "tAddress": "t1.....", ?

**Comment by zzzpotato** [comment]
Send 1 ZEL to your first t address in the config and see if it completes.

**Comment by angona2** [comment]
@c2h2 

Not the same.

@zzzpotato 

Trying this in a few moments.

**Comment by angona2** [comment]
@zzzpotato Sending a coin into the first address in coin.json has appeared to solve the issue. Any reason that this occurred or will I have to do something similar for other currencies that experience this issue?

Side note... I have also solved for multiple blocks of komodo and BTCP without this issue.

**Comment by angona2** [comment]
@zzzpotato Does not appear to have fixed it. The pool shielded the payment from the exchange I purchased zelcash on and then continued to display the same error message for the block solved.

**Comment by c2h2** [comment]
can be many problems, can you see your coin on the explorer? the 2 t-addresses

**Comment by angona2** [comment]
@c2h2
@zzzpotato

The problem has solved itself. After around 1800 confirmations it was accepted and I do believe sending the 1 coin to the first t-address was the trick. Is there something on the software side of things we could do to rid of this problem for good without having to send a coin?

**Comment by c2h2** [comment]
@angona2 happened to me before, the trick is to pay some coins, but the root cause could be round off error or something wrong in the config.
