### ISSUE TITLE
clearing operation ids due to empty result set

### ISSUE THREAD

**Issue by angona2** [z-classic/z-nomp#361]
I am using a fork of Z-Nomp called zh-nomp.

So first a block of bitcoinz was found, then began to shield, and finally got the line "clearing operation ids due to empty result set" for bitcoinz. Does anybody know why this line came up? It did not appear as an error (red message) but a yellow message. 

There was also 100 unconfirmed coins when I did z_getoperationstatus as well as getwalletinfo from the coin file during the shielding process, and I have yet to receive any of the 12,500 coins that is supposed to come from a bitcoinz block reward.

**Comment by TheComputerGenie** [comment]
> I am using a fork of Z-Nomp called zh-nomp.

then why are you here instead of there?
