### ISSUE TITLE
License is incorrect

### ISSUE THREAD

**Issue by webworker01** [z-classic/z-nomp#371]
You can't take GPL 2.0 software and license it as MIT

**Comment by Jerry170617** [comment]
Can you dig normally after zcash 2.0?

**Comment by nimbosa** [comment]
Yes @webworker01, I can confirm that this is correct: https://github.com/zone117x/node-open-mining-portal/blob/master/LICENSE; it cannot be changed EXCEPT by the original author of NOMP but the change even then would not be retroactive. Code licensed under GPL2 would remain under GPL2. We will revert the commit that changed this in our repo.

**Comment by nimbosa** [comment]
Thanks for noticing.

**Comment by webworker01** [comment]
Thanks, repo is still incorrectly licensed.

**Comment by nimbosa** [comment]
the license was updated on the dev branch and will be in master/production on the next release (overdue) @webworker01
