### ISSUE TITLE
Show pending rewards for pool workers

### ISSUE THREAD

**Issue by joshuayabut** [z-classic/z-nomp#45]
Adding this issue to keep track, there needs to be a way to show pending and issued rewards for pool workers.

**Comment by aayanl** [comment]
UNOMP seems to get the job done by using webdis and shell scripts, imo thats something to be avoided https://github.com/UNOMP/unified-node-open-mining-portal/tree/master/multipool

**Comment by joshuayabut** [comment]
Agreed I think we can just pull it out of redis natively. I'll have another look again this weekend, I got distracted last night fixing hash rates :)

**Comment by ceozero** [comment]
How to refuse to share wireless. @aayanl  @joshuayabut

**Comment by sennevb** [comment]
This can be put out of redis, only have this issues:
- Total paid amount is held, but not each payments, so we cannnot make history with payments (i think we need to setup second redis database for that)
- users are asking to make workers, so they can see stats per worker, this needs to be implemented also

**Comment by sonicdx10** [comment]
hope to see that soon ;D

**Comment by gblass** [comment]
any update on this?

**Comment by sennevb** [comment]
Allready fixed
