### ISSUE TITLE
Lacking SSL/TLS Support

### ISSUE THREAD

**Issue by joshuayabut** [z-classic/z-nomp#52]
Adding this so it can be tracked.

**Comment by Aleix-Oto** [comment]
its possible use z-nomp with SSL??

**Comment by aayanl** [comment]
Frontend still lacks TLS

**Comment by fittsy** [comment]
You also will need to remove your insecure loading of assets. You are loading several assets via http:// which break https://

For example:  _z-nomp/website/index.html_
`<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>`

`<iframe src="http`://ghbtns.com/github-btn.html?user=joshuayabut&repo=z-nomp&type=watch&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="140" height="20"></iframe>`

**Comment by aayanl** [comment]
#123
