### ISSUE TITLE
Solo Config Option

### ISSUE THREAD

**Issue by dlehenky** [z-classic/z-nomp#81]
Is there any chance that a config option for solo mining might be added? Basically, for solo mining, I'd like the proxy to simple interface the miners' stratum dialog with the local wallet node. So, no shares, no solution validation, no Web reporting, no database, just straight up protocol exchange. Of course, keep the blocknotify cli interface, so no polling is needed for new blocks. Just lean and mean. Is that possible?

-Thanks
  David

**Comment by aayanl** [comment]
There's no option for that but it will be an upcoming feature

**Comment by dlehenky** [comment]
Thanks! I currently solo mine with it, but there’s just sooo much extra functionality that a solo miner just doesn’t need. For solo, the most important thing is getting the work to the miners - fast, and getting the block solutions to the network node - fast. Personally, the only metric I need to see is how many blocks were found.

**Comment by aayanl** [comment]
https://github.com/aayanl/equihash-solomining
