### ISSUE TITLE
Job timeout

### ISSUE THREAD

**Issue by JackMiner153** [z-classic/z-nomp#87]
Error in the last version
ZEC: Stratum - connecting to '192.168.2.2' <192.168.2.2> port 3032
ZEC: Stratum - Connected (192.168.2.2:3032) (unsecure)
ZEC: Job timeout, disconnect, retry in 20 sec...

**Comment by aayanl** [comment]
can you make a new config using the new examples?

**Comment by JackMiner153** [comment]
i'm already did it
"tlsOptions": {
        "enabled": false,
        "serverKey":"",
        "serverCert":"",
        "ca":""
    },

"ports": {
        "3032": {
            "diff": 0.05,
            "tls": false,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

**Comment by netsmarts** [comment]
Same here ...

**Comment by netsmarts** [comment]
into z-nomp directory 

**#~/z-nomp# git pull**
remote: Counting objects: 16, done.
remote: Total 16 (delta 11), reused 11 (delta 11), pack-reused 5
Unpacking objects: 100% (16/16), done.
From https://github.com/joshuayabut/node-open-mining-portal
   9199a6e..69cae62  master     -> origin/master
 * [new branch]      front-end-ssl -> origin/front-end-ssl
Updating 9199a6e..69cae62
Fast-forward
 README.md                               |  6 +++---
 package.json                            | 10 ++++++----
 pool_configs/zcash_example.json         |  8 ++++++++
 pool_configs/zcash_testnet_example.json |  8 ++++++++
 pool_configs/zclassic_example.json      |  8 ++++++++
 5 files changed, 33 insertions(+), 7 deletions(-)

**#~/z-nomp# rm -r node_modules**
**#~/z-nomp# npm update**

after update ...........

make: Leaving directory '/home/z-nomp/node_modules/bignum/build'
z-nomp@0.0.4 /home/z-nomp
├── async@2.1.4 
├── bignum@0.12.5 
├── body-parser@1.16.1 
├── colors@1.1.2 
├── compression@1.6.2 
├── dateformat@2.0.0 
├── dot@1.1.1 
├── express@4.14.1 
├── extend@3.0.0 
├── mysql@2.13.0 
├── node-json-minify@1.0.0 
├── node-watch@0.4.1 
├── nonce@1.0.4 
├── redis@2.6.5 
├── request@2.79.0 
└── stratum-pool@0.1.6  (git+https://github.com/z-classic/node-stratum-pool.git#a5ba489aa6aeb9d4d9126225d4d2fee11651e943)

**edit : pool_configs/zcash.json**

 "tlsOptions": {
     **"enabled": false,**
     "serverKey":"/etc/letsencrypt/live/{domain}/privkey.pem",
     "serverCert":"/etc/letsencrypt/live/{domain}/cert.pem",
     "ca":"/etc/letsencrypt/live/{domain}/chain.pem"
    },


    "ports": {
        "3020": {
            "diff": 0.05,
            **"tls": false,**
            "varDiff": {
                "minDiff": 0.01,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

with **true** and **false** stratum pool not work

**Comment by aayanl** [comment]
If you're not using TLS, connect to the startum normally, if you are, please consult your miners documentation on how to connect

**Comment by JackMiner153** [comment]
i know how to connect without TLS and previous version working fine

**Comment by netsmarts** [comment]
Before last commit also my pool working well ..
I try to remove/set false to tls options and tlsOptions but without success.

i will try to use console.log to find more information

**Comment by netsmarts** [comment]
Problem solved ..
you need to modify this **node_modules/stratum-pool/lib/stratum.js** at row 445/447

 var serversStarted = 0;
        Object.keys(options.ports).forEach(function(port){
            if (_**options.ports[port].tls = "false" || undefined**_) {
              .................................................................................
             } else if (_**options.ports[port].tls = "true"**_ ) {

it's work with **true** and **false**

please commit this, 
Regards

**Comment by aayanl** [comment]
should be fixed, remove your node_modules and then `npm install`

**Comment by aayanl** [comment]
Confirmed with #88 that this works, thanks
