### ISSUE TITLE
Pool not working with Zcash 1.0.6

### ISSUE THREAD

**Issue by erezrb** [z-classic/z-nomp#89]
hi,

Pool not working with Zcash 1.0.6,

got payment issue first but then all the pool not respond to remote mining software.

thank's :-)

/root/z-nomp/node_modules/stratum-pool/lib/stratum.js:447
        if (options.tlsOptions.enabled == true) {
                              ^

TypeError: Cannot read property 'enabled' of undefined
    at init (/root/z-nomp/node_modules/stratum-pool/lib/stratum.js:447:31)
    at new StratumServer (/root/z-nomp/node_modules/stratum-pool/lib/stratum.js:476:7)
    at StartStratumServer (/root/z-nomp/node_modules/stratum-pool/lib/pool.js:442:31)
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:55:25
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:91:13
    at /root/z-nomp/node_modules/stratum-pool/lib/pool.js:579:25
    at itemFinished (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:155:36)
    at /root/z-nomp/node_modules/stratum-pool/lib/daemon.js:169:17
    at parseJson (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/z-nomp/node_modules/stratum-pool/lib/daemon.js:95:17)
2017-02-18 15:43:43 [Master]    [PoolSpawner] Fork 2 died, spawning replacement worker...

**Comment by aayanl** [comment]
can you remove your node_modules and do `npm install`?

**Comment by erezrb** [comment]
Hi,

i try this, did not resolved the error,  getting the same error.

**Comment by aayanl** [comment]
can you use a new config from the examples?

**Comment by joshuayabut** [comment]
This should be fixed now. Please run the code below to update:
```
git pull
npm update
npm install
```

https://github.com/z-classic/node-stratum-pool/commit/c755863595fd630d55a6e4c8f4886b98468a978f

**Comment by erezrb** [comment]
ok, thank you
when i do npm update i'm getting:

../src/equi/equi.c: In function 'isZero':
../src/equi/equi.c:78:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < len; i++) {
                     ^
  CC(target) Release/obj.target/libequi/src/equi/endian.o
  SOLINK(target) Release/obj.target/equi.so
  COPY Release/equi.so
  CXX(target) Release/obj.target/equihashverify/equihashverify.o
In file included from ../equihashverify.cc:8:0:
../src/equi/equi.h:22:13: warning: 'void digestInit(crypto_generichash_blake2b_state*, int, int)' declared 'static' but never defined [-Wunused-function]
 static void digestInit(crypto_generichash_blake2b_state *S, const int n, const
             ^
../src/equi/equi.h:24:13: warning: 'void expandArray(const unsigned char*, size_t, unsigned char*, size_t, size_t, size_t)' declared 'static' but never defined [-Wunused-function]
 static void expandArray(const unsigned char *in, const size_t in_len,
             ^
../src/equi/equi.h:28:12: warning: 'int isZero(const uint8_t*, size_t)' declared 'static' but never defined [-Wunused-function]
 static int isZero(const uint8_t *hash, size_t len);
            ^
../src/equi/equi.h:30:13: warning: 'void generateHash(crypto_generichash_blake2b_state*, uint32_t, uint8_t*, size_t)' declared 'static' but never defined [-Wunused-function]
 static void generateHash(crypto_generichash_blake2b_state *S, const uint32_t g,
             ^
  SOLINK_MODULE(target) Release/obj.target/equihashverify.node
  COPY Release/equihashverify.node
----------------------------------------------------------------------------

and when i start the pool - i'm geting:

/root/z-nomp/node_modules/bs58check/index.js:48
  if (!payload) throw new Error('Invalid checksum')
                ^

Error: Invalid checksum
    at Object.decode (/root/z-nomp/node_modules/bs58check/index.js:48:23)
    at Object.fromBase58Check (/root/z-nomp/node_modules/bitcoinjs-lib-zcash/src/address.js:8:27)
    at Object.exports.createGeneration (/root/z-nomp/node_modules/stratum-pool/lib/transactions.js:87:46)
    at new BlockTemplate (/root/z-nomp/node_modules/stratum-pool/lib/bl

**Comment by joshuayabut** [comment]
Almost there! That npm update error isn't anything to worry about.

To fix the invalid checksum error you'll need to make sure that all of the addresses are correct in your config file and have quotations around them. If you post your config file (with the passwords removed I can steer you in the right direction)

**Comment by erezrb** [comment]
ok guys, thank you for all your help,

i delete all and reinstall it again and it's working now.

thank you for great work guys, i appreciate it :-)
