### ISSUE TITLE
MPOS mode

### ISSUE THREAD

**Issue by EliteMobb79** [z-classic/z-nomp#90]
I have z-nomp installed and running but I am having issues with consistency. One time I connect and the miner will run, other times I get an authentication error with the same config. I am using z-mpos with this setup and I have verified I have a stable mysql connection and can reach everything from the pool server. I cant get MRR or NH to validate the pool either. They both return with authentication errors as well. I have disabled username verification in the z-nomp config as well. Verified the worker name and pass are correct as well.  If I restart the pool with the miner running (with the authentication error) most of the time it will connect and run fine until stopped and restarted at which time the pool has to be restarted to connect again.

Anyone have any insight why the issue with the pool validating workers when its turned off? I am running several pools with our standard uNOMP software and dont see any validation changes between ours and this port in from it other than the TLS which is turned off in z-nomp.

**Comment by aayanl** [comment]
Just as you made this issue, I made a commit that fixes this lol

remove node_modules and then do `npm install`

https://github.com/z-classic/node-stratum-pool/commit/5e4e57d52435aa188b094b2de45de6de7a6b7927

**Comment by EliteMobb79** [comment]
Seems I have good timing with that. 2 for 2 so far. lol Thanks for the quick reply. Applying the fix now.

**Comment by EliteMobb79** [comment]
Excellent work. That looks more like it. Its connecting now. Validated on MRR and NH as well. Its also showing the worker update correctly now instead of the worker=unknown.
