### ISSUE TITLE
Payment - web - stats?

### ISSUE THREAD

**Issue by sonicdx10** [z-classic/z-nomp#95]
2017-03-11 15:42:21 [Payments]  [zdash] Could not update zcash stats to redis {"command":"EXEC","code":"EXECABORT","errors":[{"command":"HSET","args":["zdash:stats","networkSols"],"code":"ERR","position":2}]}

**Comment by sonicdx10** [comment]
flushall did not work

**Comment by aayanl** [comment]
update z-nomp and set zdash's coin to zdash, https://github.com/z-classic/z-nomp/commit/017731bbe71f08ae14a901f4932f762000155f33

**Comment by sonicdx10** [comment]
No, its not working, did fresh install/compile/etc

**Comment by sonicdx10** [comment]
yep, couldn't get it to refresh statics on rpc/web (just in Zdash) (Zec, Zcl are working ok) (Komodo won't run with this line // generate the fees and coinbase tx var blockReward = (this.rpcData.miner + **this.rpcData.founders**) * 100000000;)
