### ISSUE TITLE
Mining Day

### ISSUE THREAD

**Issue by sonicdx10** [z-classic/z-nomp#98]
If I minned all day long with like 4k-6k sols and theres still no information abaout any balance neither in z_gettotalbalance or getbalance or listtransactions or listaddressgroupings ... what does it mena, is it a lost day? or is there any chance to get that hashing?

**Comment by sonicdx10** [comment]
https://explorer.zcha.in/accounts/t1f4Sn1GmXLoG5sufmJtEuSEMs9MEzFuhnH no inputs? just outputs? automatic outputs? so i lost my money?

**Comment by sonicdx10** [comment]
with last git update i get no coins from pool

**Comment by aayanl** [comment]
I need a little more info, did you find a block?
